// Code generated by ent, DO NOT EDIT.

package knowledgeindex

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the knowledgeindex type in the database.
	Label = "knowledge_index"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldMilvusCollection holds the string denoting the milvus_collection field in the database.
	FieldMilvusCollection = "milvus_collection"
	// FieldEmbeddingModel holds the string denoting the embedding_model field in the database.
	FieldEmbeddingModel = "embedding_model"
	// FieldEmbeddingDimensions holds the string denoting the embedding_dimensions field in the database.
	FieldEmbeddingDimensions = "embedding_dimensions"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldActivatedAt holds the string denoting the activated_at field in the database.
	FieldActivatedAt = "activated_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the knowledgeindex in the database.
	Table = "knowledge_indexes"
)

// Columns holds all SQL columns for knowledgeindex fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldMilvusCollection,
	FieldEmbeddingModel,
	FieldEmbeddingDimensions,
	FieldStatus,
	FieldActivatedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusBUILDING is the default value of the Status enum.
const DefaultStatus = StatusBUILDING

// Status values.
const (
	StatusBUILDING Status = "BUILDING"
	StatusACTIVE   Status = "ACTIVE"
	StatusRETIRED  Status = "RETIRED"
	StatusFAILED   Status = "FAILED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusBUILDING, StatusACTIVE, StatusRETIRED, StatusFAILED:
		return nil
	default:
		return fmt.Errorf("knowledgeindex: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the KnowledgeIndex queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByMilvusCollection orders the results by the milvus_collection field.
func ByMilvusCollection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMilvusCollection, opts...).ToFunc()
}

// ByEmbeddingModel orders the results by the embedding_model field.
func ByEmbeddingModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmbeddingModel, opts...).ToFunc()
}

// ByEmbeddingDimensions orders the results by the embedding_dimensions field.
func ByEmbeddingDimensions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmbeddingDimensions, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByActivatedAt orders the results by the activated_at field.
func ByActivatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivatedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
