// Code generated by ent, DO NOT EDIT.

package documentchunk

import (
	"eino-quickstart/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLTE(FieldID, id))
}

// ChunkIndex applies equality check predicate on the "chunk_index" field. It's identical to ChunkIndexEQ.
func ChunkIndex(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldChunkIndex, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldContent, v))
}

// HeadingPath applies equality check predicate on the "heading_path" field. It's identical to HeadingPathEQ.
func HeadingPath(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldHeadingPath, v))
}

// IndexedAt applies equality check predicate on the "indexed_at" field. It's identical to IndexedAtEQ.
func IndexedAt(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldIndexedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldCreatedAt, v))
}

// ChunkIndexEQ applies the EQ predicate on the "chunk_index" field.
func ChunkIndexEQ(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldChunkIndex, v))
}

// ChunkIndexNEQ applies the NEQ predicate on the "chunk_index" field.
func ChunkIndexNEQ(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNEQ(FieldChunkIndex, v))
}

// ChunkIndexIn applies the In predicate on the "chunk_index" field.
func ChunkIndexIn(vs ...int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIn(FieldChunkIndex, vs...))
}

// ChunkIndexNotIn applies the NotIn predicate on the "chunk_index" field.
func ChunkIndexNotIn(vs ...int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotIn(FieldChunkIndex, vs...))
}

// ChunkIndexGT applies the GT predicate on the "chunk_index" field.
func ChunkIndexGT(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGT(FieldChunkIndex, v))
}

// ChunkIndexGTE applies the GTE predicate on the "chunk_index" field.
func ChunkIndexGTE(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGTE(FieldChunkIndex, v))
}

// ChunkIndexLT applies the LT predicate on the "chunk_index" field.
func ChunkIndexLT(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLT(FieldChunkIndex, v))
}

// ChunkIndexLTE applies the LTE predicate on the "chunk_index" field.
func ChunkIndexLTE(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLTE(FieldChunkIndex, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldContainsFold(FieldContent, v))
}

// HeadingPathEQ applies the EQ predicate on the "heading_path" field.
func HeadingPathEQ(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldHeadingPath, v))
}

// HeadingPathNEQ applies the NEQ predicate on the "heading_path" field.
func HeadingPathNEQ(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNEQ(FieldHeadingPath, v))
}

// HeadingPathIn applies the In predicate on the "heading_path" field.
func HeadingPathIn(vs ...string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIn(FieldHeadingPath, vs...))
}

// HeadingPathNotIn applies the NotIn predicate on the "heading_path" field.
func HeadingPathNotIn(vs ...string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotIn(FieldHeadingPath, vs...))
}

// HeadingPathGT applies the GT predicate on the "heading_path" field.
func HeadingPathGT(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGT(FieldHeadingPath, v))
}

// HeadingPathGTE applies the GTE predicate on the "heading_path" field.
func HeadingPathGTE(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGTE(FieldHeadingPath, v))
}

// HeadingPathLT applies the LT predicate on the "heading_path" field.
func HeadingPathLT(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLT(FieldHeadingPath, v))
}

// HeadingPathLTE applies the LTE predicate on the "heading_path" field.
func HeadingPathLTE(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLTE(FieldHeadingPath, v))
}

// HeadingPathContains applies the Contains predicate on the "heading_path" field.
func HeadingPathContains(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldContains(FieldHeadingPath, v))
}

// HeadingPathHasPrefix applies the HasPrefix predicate on the "heading_path" field.
func HeadingPathHasPrefix(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldHasPrefix(FieldHeadingPath, v))
}

// HeadingPathHasSuffix applies the HasSuffix predicate on the "heading_path" field.
func HeadingPathHasSuffix(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldHasSuffix(FieldHeadingPath, v))
}

// HeadingPathIsNil applies the IsNil predicate on the "heading_path" field.
func HeadingPathIsNil() predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIsNull(FieldHeadingPath))
}

// HeadingPathNotNil applies the NotNil predicate on the "heading_path" field.
func HeadingPathNotNil() predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotNull(FieldHeadingPath))
}

// HeadingPathEqualFold applies the EqualFold predicate on the "heading_path" field.
func HeadingPathEqualFold(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEqualFold(FieldHeadingPath, v))
}

// HeadingPathContainsFold applies the ContainsFold predicate on the "heading_path" field.
func HeadingPathContainsFold(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldContainsFold(FieldHeadingPath, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotNull(FieldMetadata))
}

// VectorStatusEQ applies the EQ predicate on the "vector_status" field.
func VectorStatusEQ(v VectorStatus) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldVectorStatus, v))
}

// VectorStatusNEQ applies the NEQ predicate on the "vector_status" field.
func VectorStatusNEQ(v VectorStatus) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNEQ(FieldVectorStatus, v))
}

// VectorStatusIn applies the In predicate on the "vector_status" field.
func VectorStatusIn(vs ...VectorStatus) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIn(FieldVectorStatus, vs...))
}

// VectorStatusNotIn applies the NotIn predicate on the "vector_status" field.
func VectorStatusNotIn(vs ...VectorStatus) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotIn(FieldVectorStatus, vs...))
}

// IndexedAtEQ applies the EQ predicate on the "indexed_at" field.
func IndexedAtEQ(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldIndexedAt, v))
}

// IndexedAtNEQ applies the NEQ predicate on the "indexed_at" field.
func IndexedAtNEQ(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNEQ(FieldIndexedAt, v))
}

// IndexedAtIn applies the In predicate on the "indexed_at" field.
func IndexedAtIn(vs ...time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIn(FieldIndexedAt, vs...))
}

// IndexedAtNotIn applies the NotIn predicate on the "indexed_at" field.
func IndexedAtNotIn(vs ...time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotIn(FieldIndexedAt, vs...))
}

// IndexedAtGT applies the GT predicate on the "indexed_at" field.
func IndexedAtGT(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGT(FieldIndexedAt, v))
}

// IndexedAtGTE applies the GTE predicate on the "indexed_at" field.
func IndexedAtGTE(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGTE(FieldIndexedAt, v))
}

// IndexedAtLT applies the LT predicate on the "indexed_at" field.
func IndexedAtLT(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLT(FieldIndexedAt, v))
}

// IndexedAtLTE applies the LTE predicate on the "indexed_at" field.
func IndexedAtLTE(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLTE(FieldIndexedAt, v))
}

// IndexedAtIsNil applies the IsNil predicate on the "indexed_at" field.
func IndexedAtIsNil() predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIsNull(FieldIndexedAt))
}

// IndexedAtNotNil applies the NotNil predicate on the "indexed_at" field.
func IndexedAtNotNil() predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotNull(FieldIndexedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLTE(FieldCreatedAt, v))
}

// HasDocument applies the HasEdge predicate on the "document" edge.
func HasDocument() predicate.DocumentChunk {
	return predicate.DocumentChunk(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DocumentTable, DocumentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDocumentWith applies the HasEdge predicate on the "document" edge with a given conditions (other predicates).
func HasDocumentWith(preds ...predicate.Document) predicate.DocumentChunk {
	return predicate.DocumentChunk(func(s *sql.Selector) {
		step := newDocumentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DocumentChunk) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DocumentChunk) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DocumentChunk) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.NotPredicates(p))
}
