// Code generated by ent, DO NOT EDIT.

package approval

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the approval type in the database.
	Label = "approval"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldApprovalID holds the string denoting the approval_id field in the database.
	FieldApprovalID = "approval_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldTurnID holds the string denoting the turn_id field in the database.
	FieldTurnID = "turn_id"
	// FieldTool holds the string denoting the tool field in the database.
	FieldTool = "tool"
	// FieldArgumentsHash holds the string denoting the arguments_hash field in the database.
	FieldArgumentsHash = "arguments_hash"
	// FieldDisplayArguments holds the string denoting the display_arguments field in the database.
	FieldDisplayArguments = "display_arguments"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldRequestedBy holds the string denoting the requested_by field in the database.
	FieldRequestedBy = "requested_by"
	// FieldDecidedAt holds the string denoting the decided_at field in the database.
	FieldDecidedAt = "decided_at"
	// FieldExecutedAt holds the string denoting the executed_at field in the database.
	FieldExecutedAt = "executed_at"
	// FieldDecidedBy holds the string denoting the decided_by field in the database.
	FieldDecidedBy = "decided_by"
	// FieldCheckpointID holds the string denoting the checkpoint_id field in the database.
	FieldCheckpointID = "checkpoint_id"
	// FieldInterruptID holds the string denoting the interrupt_id field in the database.
	FieldInterruptID = "interrupt_id"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the approval in the database.
	Table = "approvals"
)

// Columns holds all SQL columns for approval fields.
var Columns = []string{
	FieldID,
	FieldApprovalID,
	FieldSessionID,
	FieldRunID,
	FieldTurnID,
	FieldTool,
	FieldArgumentsHash,
	FieldDisplayArguments,
	FieldStatus,
	FieldCreatedAt,
	FieldRequestedBy,
	FieldDecidedAt,
	FieldExecutedAt,
	FieldDecidedBy,
	FieldCheckpointID,
	FieldInterruptID,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING  Status = "PENDING"
	StatusAPPROVED Status = "APPROVED"
	StatusREJECTED Status = "REJECTED"
	StatusRESUMING Status = "RESUMING"
	StatusEXECUTED Status = "EXECUTED"
	StatusEXPIRED  Status = "EXPIRED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusAPPROVED, StatusREJECTED, StatusRESUMING, StatusEXECUTED, StatusEXPIRED:
		return nil
	default:
		return fmt.Errorf("approval: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Approval queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByApprovalID orders the results by the approval_id field.
func ByApprovalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovalID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByTurnID orders the results by the turn_id field.
func ByTurnID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTurnID, opts...).ToFunc()
}

// ByTool orders the results by the tool field.
func ByTool(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTool, opts...).ToFunc()
}

// ByArgumentsHash orders the results by the arguments_hash field.
func ByArgumentsHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArgumentsHash, opts...).ToFunc()
}

// ByDisplayArguments orders the results by the display_arguments field.
func ByDisplayArguments(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayArguments, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRequestedBy orders the results by the requested_by field.
func ByRequestedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedBy, opts...).ToFunc()
}

// ByDecidedAt orders the results by the decided_at field.
func ByDecidedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDecidedAt, opts...).ToFunc()
}

// ByExecutedAt orders the results by the executed_at field.
func ByExecutedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutedAt, opts...).ToFunc()
}

// ByDecidedBy orders the results by the decided_by field.
func ByDecidedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDecidedBy, opts...).ToFunc()
}

// ByCheckpointID orders the results by the checkpoint_id field.
func ByCheckpointID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckpointID, opts...).ToFunc()
}

// ByInterruptID orders the results by the interrupt_id field.
func ByInterruptID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInterruptID, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
