// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AgentRunsColumns holds the columns for the "agent_runs" table.
	AgentRunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "run_id", Type: field.TypeString, Unique: true},
		{Name: "session_id", Type: field.TypeString},
		{Name: "requested_by", Type: field.TypeString},
		{Name: "user_message", Type: field.TypeString, Size: 2147483647},
		{Name: "checkpoint_id", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"RUNNING", "INTERRUPTED", "RESUMING", "COMPLETED", "FAILED", "EXPIRED"}, Default: "RUNNING"},
		{Name: "approval_id", Type: field.TypeString, Nullable: true},
		{Name: "error_code", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
	}
	// AgentRunsTable holds the schema information for the "agent_runs" table.
	AgentRunsTable = &schema.Table{
		Name:       "agent_runs",
		Columns:    AgentRunsColumns,
		PrimaryKey: []*schema.Column{AgentRunsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "agentrun_session_id_status",
				Unique:  false,
				Columns: []*schema.Column{AgentRunsColumns[2], AgentRunsColumns[6]},
			},
			{
				Name:    "agentrun_checkpoint_id",
				Unique:  false,
				Columns: []*schema.Column{AgentRunsColumns[5]},
			},
			{
				Name:    "agentrun_expires_at",
				Unique:  false,
				Columns: []*schema.Column{AgentRunsColumns[12]},
			},
		},
	}
	// ApprovalsColumns holds the columns for the "approvals" table.
	ApprovalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "approval_id", Type: field.TypeString, Unique: true},
		{Name: "session_id", Type: field.TypeString},
		{Name: "run_id", Type: field.TypeString, Nullable: true},
		{Name: "turn_id", Type: field.TypeString, Nullable: true},
		{Name: "tool", Type: field.TypeString},
		{Name: "arguments_hash", Type: field.TypeString, Nullable: true},
		{Name: "display_arguments", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "APPROVED", "REJECTED", "RESUMING", "EXECUTED", "EXPIRED"}, Default: "PENDING"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "requested_by", Type: field.TypeString},
		{Name: "decided_at", Type: field.TypeTime, Nullable: true},
		{Name: "executed_at", Type: field.TypeTime, Nullable: true},
		{Name: "decided_by", Type: field.TypeString, Nullable: true},
		{Name: "checkpoint_id", Type: field.TypeString, Nullable: true},
		{Name: "interrupt_id", Type: field.TypeString, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
	}
	// ApprovalsTable holds the schema information for the "approvals" table.
	ApprovalsTable = &schema.Table{
		Name:       "approvals",
		Columns:    ApprovalsColumns,
		PrimaryKey: []*schema.Column{ApprovalsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "approval_status_expires_at",
				Unique:  false,
				Columns: []*schema.Column{ApprovalsColumns[8], ApprovalsColumns[16]},
			},
			{
				Name:    "approval_checkpoint_id",
				Unique:  false,
				Columns: []*schema.Column{ApprovalsColumns[14]},
			},
		},
	}
	// AuditEventsColumns holds the columns for the "audit_events" table.
	AuditEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "session_id", Type: field.TypeString},
		{Name: "approval_id", Type: field.TypeString, Nullable: true},
		{Name: "event_type", Type: field.TypeString},
		{Name: "tool", Type: field.TypeString, Nullable: true},
		{Name: "payload", Type: field.TypeString, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "actor_subject", Type: field.TypeString, Nullable: true},
	}
	// AuditEventsTable holds the schema information for the "audit_events" table.
	AuditEventsTable = &schema.Table{
		Name:       "audit_events",
		Columns:    AuditEventsColumns,
		PrimaryKey: []*schema.Column{AuditEventsColumns[0]},
	}
	// ChatTurnsColumns holds the columns for the "chat_turns" table.
	ChatTurnsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "turn_id", Type: field.TypeString, Unique: true},
		{Name: "session_id", Type: field.TypeString},
		{Name: "owner_subject", Type: field.TypeString},
		{Name: "user_content", Type: field.TypeString, Size: 2147483647},
		{Name: "assistant_content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"RUNNING", "INTERRUPTED", "COMPLETED", "FAILED"}, Default: "RUNNING"},
		{Name: "approval_id", Type: field.TypeString, Nullable: true},
		{Name: "checkpoint_id", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
	}
	// ChatTurnsTable holds the schema information for the "chat_turns" table.
	ChatTurnsTable = &schema.Table{
		Name:       "chat_turns",
		Columns:    ChatTurnsColumns,
		PrimaryKey: []*schema.Column{ChatTurnsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "chatturn_session_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{ChatTurnsColumns[2], ChatTurnsColumns[9]},
			},
			{
				Name:    "chatturn_owner_subject_created_at",
				Unique:  false,
				Columns: []*schema.Column{ChatTurnsColumns[3], ChatTurnsColumns[9]},
			},
			{
				Name:    "chatturn_approval_id",
				Unique:  true,
				Columns: []*schema.Column{ChatTurnsColumns[7]},
			},
			{
				Name:    "chatturn_status_completed_at",
				Unique:  false,
				Columns: []*schema.Column{ChatTurnsColumns[6], ChatTurnsColumns[10]},
			},
		},
	}
	// CheckpointsColumns holds the columns for the "checkpoints" table.
	CheckpointsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "checkpoint_id", Type: field.TypeString, Unique: true},
		{Name: "payload", Type: field.TypeBytes},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
	}
	// CheckpointsTable holds the schema information for the "checkpoints" table.
	CheckpointsTable = &schema.Table{
		Name:       "checkpoints",
		Columns:    CheckpointsColumns,
		PrimaryKey: []*schema.Column{CheckpointsColumns[0]},
	}
	// DocumentsColumns holds the columns for the "documents" table.
	DocumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "source", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "checksum", Type: field.TypeString},
		{Name: "owner_subject", Type: field.TypeString, Default: "system"},
		{Name: "visibility", Type: field.TypeEnum, Enums: []string{"system", "private"}, Default: "system"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"ready", "indexing", "failed", "deleted"}, Default: "indexing"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "knowledge_base_id", Type: field.TypeInt},
		{Name: "folder_id", Type: field.TypeInt, Nullable: true},
	}
	// DocumentsTable holds the schema information for the "documents" table.
	DocumentsTable = &schema.Table{
		Name:       "documents",
		Columns:    DocumentsColumns,
		PrimaryKey: []*schema.Column{DocumentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "documents_knowledge_bases_documents",
				Columns:    []*schema.Column{DocumentsColumns[10]},
				RefColumns: []*schema.Column{KnowledgeBasesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "documents_knowledge_folders_documents",
				Columns:    []*schema.Column{DocumentsColumns[11]},
				RefColumns: []*schema.Column{KnowledgeFoldersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "document_knowledge_base_id_source",
				Unique:  true,
				Columns: []*schema.Column{DocumentsColumns[10], DocumentsColumns[1]},
			},
			{
				Name:    "document_owner_subject_visibility",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[5], DocumentsColumns[6]},
			},
			{
				Name:    "document_checksum",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[4]},
			},
		},
	}
	// DocumentChunksColumns holds the columns for the "document_chunks" table.
	DocumentChunksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "chunk_index", Type: field.TypeInt},
		{Name: "citation_id", Type: field.TypeString, Unique: true},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "heading_path", Type: field.TypeString, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "start_line", Type: field.TypeInt},
		{Name: "end_line", Type: field.TypeInt},
		{Name: "character_count", Type: field.TypeInt},
		{Name: "embedding_model", Type: field.TypeString},
		{Name: "vector_status", Type: field.TypeEnum, Enums: []string{"pending", "indexed", "failed", "deleting"}, Default: "pending"},
		{Name: "indexed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "document_chunks", Type: field.TypeInt},
	}
	// DocumentChunksTable holds the schema information for the "document_chunks" table.
	DocumentChunksTable = &schema.Table{
		Name:       "document_chunks",
		Columns:    DocumentChunksColumns,
		PrimaryKey: []*schema.Column{DocumentChunksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "document_chunks_documents_chunks",
				Columns:    []*schema.Column{DocumentChunksColumns[13]},
				RefColumns: []*schema.Column{DocumentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "documentchunk_chunk_index_document_chunks",
				Unique:  true,
				Columns: []*schema.Column{DocumentChunksColumns[1], DocumentChunksColumns[13]},
			},
			{
				Name:    "documentchunk_vector_status",
				Unique:  false,
				Columns: []*schema.Column{DocumentChunksColumns[10]},
			},
			{
				Name:    "documentchunk_metadata",
				Unique:  false,
				Columns: []*schema.Column{DocumentChunksColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					Types: map[string]string{
						"postgres": "GIN",
					},
				},
			},
		},
	}
	// KnowledgeBasesColumns holds the columns for the "knowledge_bases" table.
	KnowledgeBasesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "owner_subject", Type: field.TypeString, Default: "system"},
		{Name: "visibility", Type: field.TypeEnum, Enums: []string{"system", "private"}, Default: "system"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"ACTIVE", "DISABLED"}, Default: "ACTIVE"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// KnowledgeBasesTable holds the schema information for the "knowledge_bases" table.
	KnowledgeBasesTable = &schema.Table{
		Name:       "knowledge_bases",
		Columns:    KnowledgeBasesColumns,
		PrimaryKey: []*schema.Column{KnowledgeBasesColumns[0]},
	}
	// KnowledgeFoldersColumns holds the columns for the "knowledge_folders" table.
	KnowledgeFoldersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "sort", Type: field.TypeInt, Default: 0},
		{Name: "knowledge_base_id", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "knowledge_base_folders", Type: field.TypeInt},
		{Name: "parent_id", Type: field.TypeInt, Nullable: true},
	}
	// KnowledgeFoldersTable holds the schema information for the "knowledge_folders" table.
	KnowledgeFoldersTable = &schema.Table{
		Name:       "knowledge_folders",
		Columns:    KnowledgeFoldersColumns,
		PrimaryKey: []*schema.Column{KnowledgeFoldersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "knowledge_folders_knowledge_bases_folders",
				Columns:    []*schema.Column{KnowledgeFoldersColumns[7]},
				RefColumns: []*schema.Column{KnowledgeBasesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "knowledge_folders_knowledge_folders_children",
				Columns:    []*schema.Column{KnowledgeFoldersColumns[8]},
				RefColumns: []*schema.Column{KnowledgeFoldersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "knowledgefolder_knowledge_base_id_parent_id",
				Unique:  false,
				Columns: []*schema.Column{KnowledgeFoldersColumns[4], KnowledgeFoldersColumns[8]},
			},
			{
				Name:    "knowledgefolder_knowledge_base_id_path",
				Unique:  true,
				Columns: []*schema.Column{KnowledgeFoldersColumns[4], KnowledgeFoldersColumns[2]},
			},
		},
	}
	// KnowledgeIndexesColumns holds the columns for the "knowledge_indexes" table.
	KnowledgeIndexesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "milvus_collection", Type: field.TypeString, Unique: true},
		{Name: "embedding_model", Type: field.TypeString},
		{Name: "embedding_dimensions", Type: field.TypeInt},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"BUILDING", "ACTIVE", "RETIRED", "FAILED"}, Default: "BUILDING"},
		{Name: "activated_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// KnowledgeIndexesTable holds the schema information for the "knowledge_indexes" table.
	KnowledgeIndexesTable = &schema.Table{
		Name:       "knowledge_indexes",
		Columns:    KnowledgeIndexesColumns,
		PrimaryKey: []*schema.Column{KnowledgeIndexesColumns[0]},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "session_id", Type: field.TypeString, Unique: true},
		{Name: "owner_subject", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
	}
	// SessionMessagesColumns holds the columns for the "session_messages" table.
	SessionMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "role", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "session_messages", Type: field.TypeInt},
	}
	// SessionMessagesTable holds the schema information for the "session_messages" table.
	SessionMessagesTable = &schema.Table{
		Name:       "session_messages",
		Columns:    SessionMessagesColumns,
		PrimaryKey: []*schema.Column{SessionMessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "session_messages_sessions_messages",
				Columns:    []*schema.Column{SessionMessagesColumns[4]},
				RefColumns: []*schema.Column{SessionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// VectorOutboxesColumns holds the columns for the "vector_outboxes" table.
	VectorOutboxesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "chunk_id", Type: field.TypeInt64, Unique: true},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"upsert", "delete"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "processing", "done", "failed"}, Default: "pending"},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "available_at", Type: field.TypeTime},
		{Name: "locked_until", Type: field.TypeTime, Nullable: true},
		{Name: "last_error", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// VectorOutboxesTable holds the schema information for the "vector_outboxes" table.
	VectorOutboxesTable = &schema.Table{
		Name:       "vector_outboxes",
		Columns:    VectorOutboxesColumns,
		PrimaryKey: []*schema.Column{VectorOutboxesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "vectoroutbox_status_available_at",
				Unique:  false,
				Columns: []*schema.Column{VectorOutboxesColumns[3], VectorOutboxesColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AgentRunsTable,
		ApprovalsTable,
		AuditEventsTable,
		ChatTurnsTable,
		CheckpointsTable,
		DocumentsTable,
		DocumentChunksTable,
		KnowledgeBasesTable,
		KnowledgeFoldersTable,
		KnowledgeIndexesTable,
		SessionsTable,
		SessionMessagesTable,
		VectorOutboxesTable,
	}
)

func init() {
	DocumentsTable.ForeignKeys[0].RefTable = KnowledgeBasesTable
	DocumentsTable.ForeignKeys[1].RefTable = KnowledgeFoldersTable
	DocumentChunksTable.ForeignKeys[0].RefTable = DocumentsTable
	KnowledgeFoldersTable.ForeignKeys[0].RefTable = KnowledgeBasesTable
	KnowledgeFoldersTable.ForeignKeys[1].RefTable = KnowledgeFoldersTable
	SessionsTable.Annotation = &entsql.Annotation{
		Table: "sessions",
	}
	SessionMessagesTable.ForeignKeys[0].RefTable = SessionsTable
	SessionMessagesTable.Annotation = &entsql.Annotation{
		Table: "session_messages",
	}
}
