// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eino-quickstart/ent/agentdataset"
	"eino-quickstart/ent/dataset"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AgentDatasetCreate is the builder for creating a AgentDataset entity.
type AgentDatasetCreate struct {
	config
	mutation *AgentDatasetMutation
	hooks    []Hook
}

// SetSubject sets the "subject" field.
func (_c *AgentDatasetCreate) SetSubject(v string) *AgentDatasetCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetDatasetID sets the "dataset_id" field.
func (_c *AgentDatasetCreate) SetDatasetID(v uint64) *AgentDatasetCreate {
	_c.mutation.SetDatasetID(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AgentDatasetCreate) SetCreatedBy(v string) *AgentDatasetCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentDatasetCreate) SetCreatedAt(v time.Time) *AgentDatasetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentDatasetCreate) SetNillableCreatedAt(v *time.Time) *AgentDatasetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetDataset sets the "dataset" edge to the Dataset entity.
func (_c *AgentDatasetCreate) SetDataset(v *Dataset) *AgentDatasetCreate {
	return _c.SetDatasetID(v.ID)
}

// Mutation returns the AgentDatasetMutation object of the builder.
func (_c *AgentDatasetCreate) Mutation() *AgentDatasetMutation {
	return _c.mutation
}

// Save creates the AgentDataset in the database.
func (_c *AgentDatasetCreate) Save(ctx context.Context) (*AgentDataset, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentDatasetCreate) SaveX(ctx context.Context) *AgentDataset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentDatasetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentDatasetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentDatasetCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agentdataset.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentDatasetCreate) check() error {
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "AgentDataset.subject"`)}
	}
	if _, ok := _c.mutation.DatasetID(); !ok {
		return &ValidationError{Name: "dataset_id", err: errors.New(`ent: missing required field "AgentDataset.dataset_id"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "AgentDataset.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentDataset.created_at"`)}
	}
	if len(_c.mutation.DatasetIDs()) == 0 {
		return &ValidationError{Name: "dataset", err: errors.New(`ent: missing required edge "AgentDataset.dataset"`)}
	}
	return nil
}

func (_c *AgentDatasetCreate) sqlSave(ctx context.Context) (*AgentDataset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = uint64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentDatasetCreate) createSpec() (*AgentDataset, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentDataset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentdataset.Table, sqlgraph.NewFieldSpec(agentdataset.FieldID, field.TypeUint64))
	)
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(agentdataset.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(agentdataset.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agentdataset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DatasetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentdataset.DatasetTable,
			Columns: []string{agentdataset.DatasetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dataset.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DatasetID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentDatasetCreateBulk is the builder for creating many AgentDataset entities in bulk.
type AgentDatasetCreateBulk struct {
	config
	err      error
	builders []*AgentDatasetCreate
}

// Save creates the AgentDataset entities in the database.
func (_c *AgentDatasetCreateBulk) Save(ctx context.Context) ([]*AgentDataset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentDataset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentDatasetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentDatasetCreateBulk) SaveX(ctx context.Context) []*AgentDataset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentDatasetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentDatasetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
