// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eino-quickstart/ent/agentknowledgebase"
	"eino-quickstart/ent/knowledgebase"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AgentKnowledgeBaseCreate is the builder for creating a AgentKnowledgeBase entity.
type AgentKnowledgeBaseCreate struct {
	config
	mutation *AgentKnowledgeBaseMutation
	hooks    []Hook
}

// SetSubject sets the "subject" field.
func (_c *AgentKnowledgeBaseCreate) SetSubject(v string) *AgentKnowledgeBaseCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetKnowledgeBaseID sets the "knowledge_base_id" field.
func (_c *AgentKnowledgeBaseCreate) SetKnowledgeBaseID(v uint64) *AgentKnowledgeBaseCreate {
	_c.mutation.SetKnowledgeBaseID(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AgentKnowledgeBaseCreate) SetCreatedBy(v string) *AgentKnowledgeBaseCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentKnowledgeBaseCreate) SetCreatedAt(v time.Time) *AgentKnowledgeBaseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentKnowledgeBaseCreate) SetNillableCreatedAt(v *time.Time) *AgentKnowledgeBaseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetKnowledgeBase sets the "knowledge_base" edge to the KnowledgeBase entity.
func (_c *AgentKnowledgeBaseCreate) SetKnowledgeBase(v *KnowledgeBase) *AgentKnowledgeBaseCreate {
	return _c.SetKnowledgeBaseID(v.ID)
}

// Mutation returns the AgentKnowledgeBaseMutation object of the builder.
func (_c *AgentKnowledgeBaseCreate) Mutation() *AgentKnowledgeBaseMutation {
	return _c.mutation
}

// Save creates the AgentKnowledgeBase in the database.
func (_c *AgentKnowledgeBaseCreate) Save(ctx context.Context) (*AgentKnowledgeBase, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentKnowledgeBaseCreate) SaveX(ctx context.Context) *AgentKnowledgeBase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentKnowledgeBaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentKnowledgeBaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentKnowledgeBaseCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agentknowledgebase.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentKnowledgeBaseCreate) check() error {
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "AgentKnowledgeBase.subject"`)}
	}
	if _, ok := _c.mutation.KnowledgeBaseID(); !ok {
		return &ValidationError{Name: "knowledge_base_id", err: errors.New(`ent: missing required field "AgentKnowledgeBase.knowledge_base_id"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "AgentKnowledgeBase.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentKnowledgeBase.created_at"`)}
	}
	if len(_c.mutation.KnowledgeBaseIDs()) == 0 {
		return &ValidationError{Name: "knowledge_base", err: errors.New(`ent: missing required edge "AgentKnowledgeBase.knowledge_base"`)}
	}
	return nil
}

func (_c *AgentKnowledgeBaseCreate) sqlSave(ctx context.Context) (*AgentKnowledgeBase, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = uint64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentKnowledgeBaseCreate) createSpec() (*AgentKnowledgeBase, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentKnowledgeBase{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentknowledgebase.Table, sqlgraph.NewFieldSpec(agentknowledgebase.FieldID, field.TypeUint64))
	)
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(agentknowledgebase.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(agentknowledgebase.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agentknowledgebase.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.KnowledgeBaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentknowledgebase.KnowledgeBaseTable,
			Columns: []string{agentknowledgebase.KnowledgeBaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.KnowledgeBaseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentKnowledgeBaseCreateBulk is the builder for creating many AgentKnowledgeBase entities in bulk.
type AgentKnowledgeBaseCreateBulk struct {
	config
	err      error
	builders []*AgentKnowledgeBaseCreate
}

// Save creates the AgentKnowledgeBase entities in the database.
func (_c *AgentKnowledgeBaseCreateBulk) Save(ctx context.Context) ([]*AgentKnowledgeBase, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentKnowledgeBase, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentKnowledgeBaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentKnowledgeBaseCreateBulk) SaveX(ctx context.Context) []*AgentKnowledgeBase {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentKnowledgeBaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentKnowledgeBaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
