// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eino-quickstart/ent/agentknowledgebase"
	"eino-quickstart/ent/knowledgebase"
	"eino-quickstart/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AgentKnowledgeBaseUpdate is the builder for updating AgentKnowledgeBase entities.
type AgentKnowledgeBaseUpdate struct {
	config
	hooks    []Hook
	mutation *AgentKnowledgeBaseMutation
}

// Where appends a list predicates to the AgentKnowledgeBaseUpdate builder.
func (_u *AgentKnowledgeBaseUpdate) Where(ps ...predicate.AgentKnowledgeBase) *AgentKnowledgeBaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKnowledgeBaseID sets the "knowledge_base_id" field.
func (_u *AgentKnowledgeBaseUpdate) SetKnowledgeBaseID(v uint64) *AgentKnowledgeBaseUpdate {
	_u.mutation.SetKnowledgeBaseID(v)
	return _u
}

// SetNillableKnowledgeBaseID sets the "knowledge_base_id" field if the given value is not nil.
func (_u *AgentKnowledgeBaseUpdate) SetNillableKnowledgeBaseID(v *uint64) *AgentKnowledgeBaseUpdate {
	if v != nil {
		_u.SetKnowledgeBaseID(*v)
	}
	return _u
}

// SetKnowledgeBase sets the "knowledge_base" edge to the KnowledgeBase entity.
func (_u *AgentKnowledgeBaseUpdate) SetKnowledgeBase(v *KnowledgeBase) *AgentKnowledgeBaseUpdate {
	return _u.SetKnowledgeBaseID(v.ID)
}

// Mutation returns the AgentKnowledgeBaseMutation object of the builder.
func (_u *AgentKnowledgeBaseUpdate) Mutation() *AgentKnowledgeBaseMutation {
	return _u.mutation
}

// ClearKnowledgeBase clears the "knowledge_base" edge to the KnowledgeBase entity.
func (_u *AgentKnowledgeBaseUpdate) ClearKnowledgeBase() *AgentKnowledgeBaseUpdate {
	_u.mutation.ClearKnowledgeBase()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentKnowledgeBaseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentKnowledgeBaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentKnowledgeBaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentKnowledgeBaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentKnowledgeBaseUpdate) check() error {
	if _u.mutation.KnowledgeBaseCleared() && len(_u.mutation.KnowledgeBaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentKnowledgeBase.knowledge_base"`)
	}
	return nil
}

func (_u *AgentKnowledgeBaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentknowledgebase.Table, agentknowledgebase.Columns, sqlgraph.NewFieldSpec(agentknowledgebase.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.KnowledgeBaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentknowledgebase.KnowledgeBaseTable,
			Columns: []string{agentknowledgebase.KnowledgeBaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KnowledgeBaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentknowledgebase.KnowledgeBaseTable,
			Columns: []string{agentknowledgebase.KnowledgeBaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentknowledgebase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentKnowledgeBaseUpdateOne is the builder for updating a single AgentKnowledgeBase entity.
type AgentKnowledgeBaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentKnowledgeBaseMutation
}

// SetKnowledgeBaseID sets the "knowledge_base_id" field.
func (_u *AgentKnowledgeBaseUpdateOne) SetKnowledgeBaseID(v uint64) *AgentKnowledgeBaseUpdateOne {
	_u.mutation.SetKnowledgeBaseID(v)
	return _u
}

// SetNillableKnowledgeBaseID sets the "knowledge_base_id" field if the given value is not nil.
func (_u *AgentKnowledgeBaseUpdateOne) SetNillableKnowledgeBaseID(v *uint64) *AgentKnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetKnowledgeBaseID(*v)
	}
	return _u
}

// SetKnowledgeBase sets the "knowledge_base" edge to the KnowledgeBase entity.
func (_u *AgentKnowledgeBaseUpdateOne) SetKnowledgeBase(v *KnowledgeBase) *AgentKnowledgeBaseUpdateOne {
	return _u.SetKnowledgeBaseID(v.ID)
}

// Mutation returns the AgentKnowledgeBaseMutation object of the builder.
func (_u *AgentKnowledgeBaseUpdateOne) Mutation() *AgentKnowledgeBaseMutation {
	return _u.mutation
}

// ClearKnowledgeBase clears the "knowledge_base" edge to the KnowledgeBase entity.
func (_u *AgentKnowledgeBaseUpdateOne) ClearKnowledgeBase() *AgentKnowledgeBaseUpdateOne {
	_u.mutation.ClearKnowledgeBase()
	return _u
}

// Where appends a list predicates to the AgentKnowledgeBaseUpdate builder.
func (_u *AgentKnowledgeBaseUpdateOne) Where(ps ...predicate.AgentKnowledgeBase) *AgentKnowledgeBaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentKnowledgeBaseUpdateOne) Select(field string, fields ...string) *AgentKnowledgeBaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentKnowledgeBase entity.
func (_u *AgentKnowledgeBaseUpdateOne) Save(ctx context.Context) (*AgentKnowledgeBase, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentKnowledgeBaseUpdateOne) SaveX(ctx context.Context) *AgentKnowledgeBase {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentKnowledgeBaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentKnowledgeBaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentKnowledgeBaseUpdateOne) check() error {
	if _u.mutation.KnowledgeBaseCleared() && len(_u.mutation.KnowledgeBaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentKnowledgeBase.knowledge_base"`)
	}
	return nil
}

func (_u *AgentKnowledgeBaseUpdateOne) sqlSave(ctx context.Context) (_node *AgentKnowledgeBase, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentknowledgebase.Table, agentknowledgebase.Columns, sqlgraph.NewFieldSpec(agentknowledgebase.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentKnowledgeBase.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentknowledgebase.FieldID)
		for _, f := range fields {
			if !agentknowledgebase.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentknowledgebase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.KnowledgeBaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentknowledgebase.KnowledgeBaseTable,
			Columns: []string{agentknowledgebase.KnowledgeBaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KnowledgeBaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentknowledgebase.KnowledgeBaseTable,
			Columns: []string{agentknowledgebase.KnowledgeBaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentKnowledgeBase{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentknowledgebase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
