// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eino-quickstart/ent/agentknowledgebase"
	"eino-quickstart/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AgentKnowledgeBaseDelete is the builder for deleting a AgentKnowledgeBase entity.
type AgentKnowledgeBaseDelete struct {
	config
	hooks    []Hook
	mutation *AgentKnowledgeBaseMutation
}

// Where appends a list predicates to the AgentKnowledgeBaseDelete builder.
func (_d *AgentKnowledgeBaseDelete) Where(ps ...predicate.AgentKnowledgeBase) *AgentKnowledgeBaseDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AgentKnowledgeBaseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentKnowledgeBaseDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AgentKnowledgeBaseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(agentknowledgebase.Table, sqlgraph.NewFieldSpec(agentknowledgebase.FieldID, field.TypeUint64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AgentKnowledgeBaseDeleteOne is the builder for deleting a single AgentKnowledgeBase entity.
type AgentKnowledgeBaseDeleteOne struct {
	_d *AgentKnowledgeBaseDelete
}

// Where appends a list predicates to the AgentKnowledgeBaseDelete builder.
func (_d *AgentKnowledgeBaseDeleteOne) Where(ps ...predicate.AgentKnowledgeBase) *AgentKnowledgeBaseDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AgentKnowledgeBaseDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{agentknowledgebase.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentKnowledgeBaseDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
