// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eino-quickstart/ent/approval"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApprovalCreate is the builder for creating a Approval entity.
type ApprovalCreate struct {
	config
	mutation *ApprovalMutation
	hooks    []Hook
}

// SetApprovalID sets the "approval_id" field.
func (_c *ApprovalCreate) SetApprovalID(v string) *ApprovalCreate {
	_c.mutation.SetApprovalID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *ApprovalCreate) SetSessionID(v string) *ApprovalCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetRunID sets the "run_id" field.
func (_c *ApprovalCreate) SetRunID(v string) *ApprovalCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableRunID(v *string) *ApprovalCreate {
	if v != nil {
		_c.SetRunID(*v)
	}
	return _c
}

// SetTurnID sets the "turn_id" field.
func (_c *ApprovalCreate) SetTurnID(v string) *ApprovalCreate {
	_c.mutation.SetTurnID(v)
	return _c
}

// SetNillableTurnID sets the "turn_id" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableTurnID(v *string) *ApprovalCreate {
	if v != nil {
		_c.SetTurnID(*v)
	}
	return _c
}

// SetTool sets the "tool" field.
func (_c *ApprovalCreate) SetTool(v string) *ApprovalCreate {
	_c.mutation.SetTool(v)
	return _c
}

// SetArgumentsHash sets the "arguments_hash" field.
func (_c *ApprovalCreate) SetArgumentsHash(v string) *ApprovalCreate {
	_c.mutation.SetArgumentsHash(v)
	return _c
}

// SetNillableArgumentsHash sets the "arguments_hash" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableArgumentsHash(v *string) *ApprovalCreate {
	if v != nil {
		_c.SetArgumentsHash(*v)
	}
	return _c
}

// SetDisplayArguments sets the "display_arguments" field.
func (_c *ApprovalCreate) SetDisplayArguments(v string) *ApprovalCreate {
	_c.mutation.SetDisplayArguments(v)
	return _c
}

// SetNillableDisplayArguments sets the "display_arguments" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableDisplayArguments(v *string) *ApprovalCreate {
	if v != nil {
		_c.SetDisplayArguments(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ApprovalCreate) SetStatus(v approval.Status) *ApprovalCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableStatus(v *approval.Status) *ApprovalCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ApprovalCreate) SetCreatedAt(v time.Time) *ApprovalCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableCreatedAt(v *time.Time) *ApprovalCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRequestedBy sets the "requested_by" field.
func (_c *ApprovalCreate) SetRequestedBy(v string) *ApprovalCreate {
	_c.mutation.SetRequestedBy(v)
	return _c
}

// SetDecidedAt sets the "decided_at" field.
func (_c *ApprovalCreate) SetDecidedAt(v time.Time) *ApprovalCreate {
	_c.mutation.SetDecidedAt(v)
	return _c
}

// SetNillableDecidedAt sets the "decided_at" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableDecidedAt(v *time.Time) *ApprovalCreate {
	if v != nil {
		_c.SetDecidedAt(*v)
	}
	return _c
}

// SetExecutedAt sets the "executed_at" field.
func (_c *ApprovalCreate) SetExecutedAt(v time.Time) *ApprovalCreate {
	_c.mutation.SetExecutedAt(v)
	return _c
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableExecutedAt(v *time.Time) *ApprovalCreate {
	if v != nil {
		_c.SetExecutedAt(*v)
	}
	return _c
}

// SetDecidedBy sets the "decided_by" field.
func (_c *ApprovalCreate) SetDecidedBy(v string) *ApprovalCreate {
	_c.mutation.SetDecidedBy(v)
	return _c
}

// SetNillableDecidedBy sets the "decided_by" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableDecidedBy(v *string) *ApprovalCreate {
	if v != nil {
		_c.SetDecidedBy(*v)
	}
	return _c
}

// SetCheckpointID sets the "checkpoint_id" field.
func (_c *ApprovalCreate) SetCheckpointID(v string) *ApprovalCreate {
	_c.mutation.SetCheckpointID(v)
	return _c
}

// SetNillableCheckpointID sets the "checkpoint_id" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableCheckpointID(v *string) *ApprovalCreate {
	if v != nil {
		_c.SetCheckpointID(*v)
	}
	return _c
}

// SetInterruptID sets the "interrupt_id" field.
func (_c *ApprovalCreate) SetInterruptID(v string) *ApprovalCreate {
	_c.mutation.SetInterruptID(v)
	return _c
}

// SetNillableInterruptID sets the "interrupt_id" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableInterruptID(v *string) *ApprovalCreate {
	if v != nil {
		_c.SetInterruptID(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ApprovalCreate) SetExpiresAt(v time.Time) *ApprovalCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ApprovalCreate) SetNillableExpiresAt(v *time.Time) *ApprovalCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// Mutation returns the ApprovalMutation object of the builder.
func (_c *ApprovalCreate) Mutation() *ApprovalMutation {
	return _c.mutation
}

// Save creates the Approval in the database.
func (_c *ApprovalCreate) Save(ctx context.Context) (*Approval, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ApprovalCreate) SaveX(ctx context.Context) *Approval {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApprovalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApprovalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ApprovalCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := approval.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := approval.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ApprovalCreate) check() error {
	if _, ok := _c.mutation.ApprovalID(); !ok {
		return &ValidationError{Name: "approval_id", err: errors.New(`ent: missing required field "Approval.approval_id"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "Approval.session_id"`)}
	}
	if _, ok := _c.mutation.Tool(); !ok {
		return &ValidationError{Name: "tool", err: errors.New(`ent: missing required field "Approval.tool"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Approval.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := approval.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Approval.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Approval.created_at"`)}
	}
	if _, ok := _c.mutation.RequestedBy(); !ok {
		return &ValidationError{Name: "requested_by", err: errors.New(`ent: missing required field "Approval.requested_by"`)}
	}
	return nil
}

func (_c *ApprovalCreate) sqlSave(ctx context.Context) (*Approval, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ApprovalCreate) createSpec() (*Approval, *sqlgraph.CreateSpec) {
	var (
		_node = &Approval{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(approval.Table, sqlgraph.NewFieldSpec(approval.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ApprovalID(); ok {
		_spec.SetField(approval.FieldApprovalID, field.TypeString, value)
		_node.ApprovalID = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(approval.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.RunID(); ok {
		_spec.SetField(approval.FieldRunID, field.TypeString, value)
		_node.RunID = &value
	}
	if value, ok := _c.mutation.TurnID(); ok {
		_spec.SetField(approval.FieldTurnID, field.TypeString, value)
		_node.TurnID = &value
	}
	if value, ok := _c.mutation.Tool(); ok {
		_spec.SetField(approval.FieldTool, field.TypeString, value)
		_node.Tool = value
	}
	if value, ok := _c.mutation.ArgumentsHash(); ok {
		_spec.SetField(approval.FieldArgumentsHash, field.TypeString, value)
		_node.ArgumentsHash = &value
	}
	if value, ok := _c.mutation.DisplayArguments(); ok {
		_spec.SetField(approval.FieldDisplayArguments, field.TypeString, value)
		_node.DisplayArguments = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(approval.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(approval.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.RequestedBy(); ok {
		_spec.SetField(approval.FieldRequestedBy, field.TypeString, value)
		_node.RequestedBy = value
	}
	if value, ok := _c.mutation.DecidedAt(); ok {
		_spec.SetField(approval.FieldDecidedAt, field.TypeTime, value)
		_node.DecidedAt = &value
	}
	if value, ok := _c.mutation.ExecutedAt(); ok {
		_spec.SetField(approval.FieldExecutedAt, field.TypeTime, value)
		_node.ExecutedAt = &value
	}
	if value, ok := _c.mutation.DecidedBy(); ok {
		_spec.SetField(approval.FieldDecidedBy, field.TypeString, value)
		_node.DecidedBy = &value
	}
	if value, ok := _c.mutation.CheckpointID(); ok {
		_spec.SetField(approval.FieldCheckpointID, field.TypeString, value)
		_node.CheckpointID = &value
	}
	if value, ok := _c.mutation.InterruptID(); ok {
		_spec.SetField(approval.FieldInterruptID, field.TypeString, value)
		_node.InterruptID = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(approval.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// ApprovalCreateBulk is the builder for creating many Approval entities in bulk.
type ApprovalCreateBulk struct {
	config
	err      error
	builders []*ApprovalCreate
}

// Save creates the Approval entities in the database.
func (_c *ApprovalCreateBulk) Save(ctx context.Context) ([]*Approval, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Approval, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApprovalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ApprovalCreateBulk) SaveX(ctx context.Context) []*Approval {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApprovalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApprovalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
