// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eino-quickstart/ent/chatturn"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatTurnCreate is the builder for creating a ChatTurn entity.
type ChatTurnCreate struct {
	config
	mutation *ChatTurnMutation
	hooks    []Hook
}

// SetTurnID sets the "turn_id" field.
func (_c *ChatTurnCreate) SetTurnID(v string) *ChatTurnCreate {
	_c.mutation.SetTurnID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *ChatTurnCreate) SetSessionID(v string) *ChatTurnCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetOwnerSubject sets the "owner_subject" field.
func (_c *ChatTurnCreate) SetOwnerSubject(v string) *ChatTurnCreate {
	_c.mutation.SetOwnerSubject(v)
	return _c
}

// SetUserContent sets the "user_content" field.
func (_c *ChatTurnCreate) SetUserContent(v string) *ChatTurnCreate {
	_c.mutation.SetUserContent(v)
	return _c
}

// SetAssistantContent sets the "assistant_content" field.
func (_c *ChatTurnCreate) SetAssistantContent(v string) *ChatTurnCreate {
	_c.mutation.SetAssistantContent(v)
	return _c
}

// SetNillableAssistantContent sets the "assistant_content" field if the given value is not nil.
func (_c *ChatTurnCreate) SetNillableAssistantContent(v *string) *ChatTurnCreate {
	if v != nil {
		_c.SetAssistantContent(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChatTurnCreate) SetStatus(v chatturn.Status) *ChatTurnCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ChatTurnCreate) SetNillableStatus(v *chatturn.Status) *ChatTurnCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetApprovalID sets the "approval_id" field.
func (_c *ChatTurnCreate) SetApprovalID(v string) *ChatTurnCreate {
	_c.mutation.SetApprovalID(v)
	return _c
}

// SetNillableApprovalID sets the "approval_id" field if the given value is not nil.
func (_c *ChatTurnCreate) SetNillableApprovalID(v *string) *ChatTurnCreate {
	if v != nil {
		_c.SetApprovalID(*v)
	}
	return _c
}

// SetCheckpointID sets the "checkpoint_id" field.
func (_c *ChatTurnCreate) SetCheckpointID(v string) *ChatTurnCreate {
	_c.mutation.SetCheckpointID(v)
	return _c
}

// SetNillableCheckpointID sets the "checkpoint_id" field if the given value is not nil.
func (_c *ChatTurnCreate) SetNillableCheckpointID(v *string) *ChatTurnCreate {
	if v != nil {
		_c.SetCheckpointID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatTurnCreate) SetCreatedAt(v time.Time) *ChatTurnCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatTurnCreate) SetNillableCreatedAt(v *time.Time) *ChatTurnCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *ChatTurnCreate) SetCompletedAt(v time.Time) *ChatTurnCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *ChatTurnCreate) SetNillableCompletedAt(v *time.Time) *ChatTurnCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// Mutation returns the ChatTurnMutation object of the builder.
func (_c *ChatTurnCreate) Mutation() *ChatTurnMutation {
	return _c.mutation
}

// Save creates the ChatTurn in the database.
func (_c *ChatTurnCreate) Save(ctx context.Context) (*ChatTurn, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatTurnCreate) SaveX(ctx context.Context) *ChatTurn {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatTurnCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatTurnCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatTurnCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := chatturn.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatturn.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatTurnCreate) check() error {
	if _, ok := _c.mutation.TurnID(); !ok {
		return &ValidationError{Name: "turn_id", err: errors.New(`ent: missing required field "ChatTurn.turn_id"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "ChatTurn.session_id"`)}
	}
	if _, ok := _c.mutation.OwnerSubject(); !ok {
		return &ValidationError{Name: "owner_subject", err: errors.New(`ent: missing required field "ChatTurn.owner_subject"`)}
	}
	if _, ok := _c.mutation.UserContent(); !ok {
		return &ValidationError{Name: "user_content", err: errors.New(`ent: missing required field "ChatTurn.user_content"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ChatTurn.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := chatturn.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChatTurn.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatTurn.created_at"`)}
	}
	return nil
}

func (_c *ChatTurnCreate) sqlSave(ctx context.Context) (*ChatTurn, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatTurnCreate) createSpec() (*ChatTurn, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatTurn{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatturn.Table, sqlgraph.NewFieldSpec(chatturn.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TurnID(); ok {
		_spec.SetField(chatturn.FieldTurnID, field.TypeString, value)
		_node.TurnID = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(chatturn.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.OwnerSubject(); ok {
		_spec.SetField(chatturn.FieldOwnerSubject, field.TypeString, value)
		_node.OwnerSubject = value
	}
	if value, ok := _c.mutation.UserContent(); ok {
		_spec.SetField(chatturn.FieldUserContent, field.TypeString, value)
		_node.UserContent = value
	}
	if value, ok := _c.mutation.AssistantContent(); ok {
		_spec.SetField(chatturn.FieldAssistantContent, field.TypeString, value)
		_node.AssistantContent = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(chatturn.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ApprovalID(); ok {
		_spec.SetField(chatturn.FieldApprovalID, field.TypeString, value)
		_node.ApprovalID = &value
	}
	if value, ok := _c.mutation.CheckpointID(); ok {
		_spec.SetField(chatturn.FieldCheckpointID, field.TypeString, value)
		_node.CheckpointID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatturn.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(chatturn.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	return _node, _spec
}

// ChatTurnCreateBulk is the builder for creating many ChatTurn entities in bulk.
type ChatTurnCreateBulk struct {
	config
	err      error
	builders []*ChatTurnCreate
}

// Save creates the ChatTurn entities in the database.
func (_c *ChatTurnCreateBulk) Save(ctx context.Context) ([]*ChatTurn, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatTurn, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatTurnMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatTurnCreateBulk) SaveX(ctx context.Context) []*ChatTurn {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatTurnCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatTurnCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
