// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eino-quickstart/ent/document"
	"eino-quickstart/ent/documentchunk"
	"eino-quickstart/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DocumentChunkUpdate is the builder for updating DocumentChunk entities.
type DocumentChunkUpdate struct {
	config
	hooks    []Hook
	mutation *DocumentChunkMutation
}

// Where appends a list predicates to the DocumentChunkUpdate builder.
func (_u *DocumentChunkUpdate) Where(ps ...predicate.DocumentChunk) *DocumentChunkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContent sets the "content" field.
func (_u *DocumentChunkUpdate) SetContent(v string) *DocumentChunkUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableContent(v *string) *DocumentChunkUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetHeadingPath sets the "heading_path" field.
func (_u *DocumentChunkUpdate) SetHeadingPath(v string) *DocumentChunkUpdate {
	_u.mutation.SetHeadingPath(v)
	return _u
}

// SetNillableHeadingPath sets the "heading_path" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableHeadingPath(v *string) *DocumentChunkUpdate {
	if v != nil {
		_u.SetHeadingPath(*v)
	}
	return _u
}

// ClearHeadingPath clears the value of the "heading_path" field.
func (_u *DocumentChunkUpdate) ClearHeadingPath() *DocumentChunkUpdate {
	_u.mutation.ClearHeadingPath()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *DocumentChunkUpdate) SetMetadata(v map[string]interface{}) *DocumentChunkUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *DocumentChunkUpdate) ClearMetadata() *DocumentChunkUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetStartLine sets the "start_line" field.
func (_u *DocumentChunkUpdate) SetStartLine(v int) *DocumentChunkUpdate {
	_u.mutation.ResetStartLine()
	_u.mutation.SetStartLine(v)
	return _u
}

// SetNillableStartLine sets the "start_line" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableStartLine(v *int) *DocumentChunkUpdate {
	if v != nil {
		_u.SetStartLine(*v)
	}
	return _u
}

// AddStartLine adds value to the "start_line" field.
func (_u *DocumentChunkUpdate) AddStartLine(v int) *DocumentChunkUpdate {
	_u.mutation.AddStartLine(v)
	return _u
}

// SetEndLine sets the "end_line" field.
func (_u *DocumentChunkUpdate) SetEndLine(v int) *DocumentChunkUpdate {
	_u.mutation.ResetEndLine()
	_u.mutation.SetEndLine(v)
	return _u
}

// SetNillableEndLine sets the "end_line" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableEndLine(v *int) *DocumentChunkUpdate {
	if v != nil {
		_u.SetEndLine(*v)
	}
	return _u
}

// AddEndLine adds value to the "end_line" field.
func (_u *DocumentChunkUpdate) AddEndLine(v int) *DocumentChunkUpdate {
	_u.mutation.AddEndLine(v)
	return _u
}

// SetCharacterCount sets the "character_count" field.
func (_u *DocumentChunkUpdate) SetCharacterCount(v int) *DocumentChunkUpdate {
	_u.mutation.ResetCharacterCount()
	_u.mutation.SetCharacterCount(v)
	return _u
}

// SetNillableCharacterCount sets the "character_count" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableCharacterCount(v *int) *DocumentChunkUpdate {
	if v != nil {
		_u.SetCharacterCount(*v)
	}
	return _u
}

// AddCharacterCount adds value to the "character_count" field.
func (_u *DocumentChunkUpdate) AddCharacterCount(v int) *DocumentChunkUpdate {
	_u.mutation.AddCharacterCount(v)
	return _u
}

// SetEmbeddingModel sets the "embedding_model" field.
func (_u *DocumentChunkUpdate) SetEmbeddingModel(v string) *DocumentChunkUpdate {
	_u.mutation.SetEmbeddingModel(v)
	return _u
}

// SetNillableEmbeddingModel sets the "embedding_model" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableEmbeddingModel(v *string) *DocumentChunkUpdate {
	if v != nil {
		_u.SetEmbeddingModel(*v)
	}
	return _u
}

// SetVectorStatus sets the "vector_status" field.
func (_u *DocumentChunkUpdate) SetVectorStatus(v documentchunk.VectorStatus) *DocumentChunkUpdate {
	_u.mutation.SetVectorStatus(v)
	return _u
}

// SetNillableVectorStatus sets the "vector_status" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableVectorStatus(v *documentchunk.VectorStatus) *DocumentChunkUpdate {
	if v != nil {
		_u.SetVectorStatus(*v)
	}
	return _u
}

// SetIndexedAt sets the "indexed_at" field.
func (_u *DocumentChunkUpdate) SetIndexedAt(v time.Time) *DocumentChunkUpdate {
	_u.mutation.SetIndexedAt(v)
	return _u
}

// SetNillableIndexedAt sets the "indexed_at" field if the given value is not nil.
func (_u *DocumentChunkUpdate) SetNillableIndexedAt(v *time.Time) *DocumentChunkUpdate {
	if v != nil {
		_u.SetIndexedAt(*v)
	}
	return _u
}

// ClearIndexedAt clears the value of the "indexed_at" field.
func (_u *DocumentChunkUpdate) ClearIndexedAt() *DocumentChunkUpdate {
	_u.mutation.ClearIndexedAt()
	return _u
}

// SetDocumentID sets the "document" edge to the Document entity by ID.
func (_u *DocumentChunkUpdate) SetDocumentID(id int) *DocumentChunkUpdate {
	_u.mutation.SetDocumentID(id)
	return _u
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *DocumentChunkUpdate) SetDocument(v *Document) *DocumentChunkUpdate {
	return _u.SetDocumentID(v.ID)
}

// Mutation returns the DocumentChunkMutation object of the builder.
func (_u *DocumentChunkUpdate) Mutation() *DocumentChunkMutation {
	return _u.mutation
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *DocumentChunkUpdate) ClearDocument() *DocumentChunkUpdate {
	_u.mutation.ClearDocument()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DocumentChunkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentChunkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DocumentChunkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentChunkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentChunkUpdate) check() error {
	if v, ok := _u.mutation.VectorStatus(); ok {
		if err := documentchunk.VectorStatusValidator(v); err != nil {
			return &ValidationError{Name: "vector_status", err: fmt.Errorf(`ent: validator failed for field "DocumentChunk.vector_status": %w`, err)}
		}
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentChunk.document"`)
	}
	return nil
}

func (_u *DocumentChunkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentchunk.Table, documentchunk.Columns, sqlgraph.NewFieldSpec(documentchunk.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(documentchunk.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeadingPath(); ok {
		_spec.SetField(documentchunk.FieldHeadingPath, field.TypeString, value)
	}
	if _u.mutation.HeadingPathCleared() {
		_spec.ClearField(documentchunk.FieldHeadingPath, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(documentchunk.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(documentchunk.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartLine(); ok {
		_spec.SetField(documentchunk.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartLine(); ok {
		_spec.AddField(documentchunk.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EndLine(); ok {
		_spec.SetField(documentchunk.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndLine(); ok {
		_spec.AddField(documentchunk.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CharacterCount(); ok {
		_spec.SetField(documentchunk.FieldCharacterCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCharacterCount(); ok {
		_spec.AddField(documentchunk.FieldCharacterCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EmbeddingModel(); ok {
		_spec.SetField(documentchunk.FieldEmbeddingModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.VectorStatus(); ok {
		_spec.SetField(documentchunk.FieldVectorStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IndexedAt(); ok {
		_spec.SetField(documentchunk.FieldIndexedAt, field.TypeTime, value)
	}
	if _u.mutation.IndexedAtCleared() {
		_spec.ClearField(documentchunk.FieldIndexedAt, field.TypeTime)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentchunk.DocumentTable,
			Columns: []string{documentchunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentchunk.DocumentTable,
			Columns: []string{documentchunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentchunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DocumentChunkUpdateOne is the builder for updating a single DocumentChunk entity.
type DocumentChunkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DocumentChunkMutation
}

// SetContent sets the "content" field.
func (_u *DocumentChunkUpdateOne) SetContent(v string) *DocumentChunkUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableContent(v *string) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetHeadingPath sets the "heading_path" field.
func (_u *DocumentChunkUpdateOne) SetHeadingPath(v string) *DocumentChunkUpdateOne {
	_u.mutation.SetHeadingPath(v)
	return _u
}

// SetNillableHeadingPath sets the "heading_path" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableHeadingPath(v *string) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetHeadingPath(*v)
	}
	return _u
}

// ClearHeadingPath clears the value of the "heading_path" field.
func (_u *DocumentChunkUpdateOne) ClearHeadingPath() *DocumentChunkUpdateOne {
	_u.mutation.ClearHeadingPath()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *DocumentChunkUpdateOne) SetMetadata(v map[string]interface{}) *DocumentChunkUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *DocumentChunkUpdateOne) ClearMetadata() *DocumentChunkUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetStartLine sets the "start_line" field.
func (_u *DocumentChunkUpdateOne) SetStartLine(v int) *DocumentChunkUpdateOne {
	_u.mutation.ResetStartLine()
	_u.mutation.SetStartLine(v)
	return _u
}

// SetNillableStartLine sets the "start_line" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableStartLine(v *int) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetStartLine(*v)
	}
	return _u
}

// AddStartLine adds value to the "start_line" field.
func (_u *DocumentChunkUpdateOne) AddStartLine(v int) *DocumentChunkUpdateOne {
	_u.mutation.AddStartLine(v)
	return _u
}

// SetEndLine sets the "end_line" field.
func (_u *DocumentChunkUpdateOne) SetEndLine(v int) *DocumentChunkUpdateOne {
	_u.mutation.ResetEndLine()
	_u.mutation.SetEndLine(v)
	return _u
}

// SetNillableEndLine sets the "end_line" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableEndLine(v *int) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetEndLine(*v)
	}
	return _u
}

// AddEndLine adds value to the "end_line" field.
func (_u *DocumentChunkUpdateOne) AddEndLine(v int) *DocumentChunkUpdateOne {
	_u.mutation.AddEndLine(v)
	return _u
}

// SetCharacterCount sets the "character_count" field.
func (_u *DocumentChunkUpdateOne) SetCharacterCount(v int) *DocumentChunkUpdateOne {
	_u.mutation.ResetCharacterCount()
	_u.mutation.SetCharacterCount(v)
	return _u
}

// SetNillableCharacterCount sets the "character_count" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableCharacterCount(v *int) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetCharacterCount(*v)
	}
	return _u
}

// AddCharacterCount adds value to the "character_count" field.
func (_u *DocumentChunkUpdateOne) AddCharacterCount(v int) *DocumentChunkUpdateOne {
	_u.mutation.AddCharacterCount(v)
	return _u
}

// SetEmbeddingModel sets the "embedding_model" field.
func (_u *DocumentChunkUpdateOne) SetEmbeddingModel(v string) *DocumentChunkUpdateOne {
	_u.mutation.SetEmbeddingModel(v)
	return _u
}

// SetNillableEmbeddingModel sets the "embedding_model" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableEmbeddingModel(v *string) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetEmbeddingModel(*v)
	}
	return _u
}

// SetVectorStatus sets the "vector_status" field.
func (_u *DocumentChunkUpdateOne) SetVectorStatus(v documentchunk.VectorStatus) *DocumentChunkUpdateOne {
	_u.mutation.SetVectorStatus(v)
	return _u
}

// SetNillableVectorStatus sets the "vector_status" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableVectorStatus(v *documentchunk.VectorStatus) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetVectorStatus(*v)
	}
	return _u
}

// SetIndexedAt sets the "indexed_at" field.
func (_u *DocumentChunkUpdateOne) SetIndexedAt(v time.Time) *DocumentChunkUpdateOne {
	_u.mutation.SetIndexedAt(v)
	return _u
}

// SetNillableIndexedAt sets the "indexed_at" field if the given value is not nil.
func (_u *DocumentChunkUpdateOne) SetNillableIndexedAt(v *time.Time) *DocumentChunkUpdateOne {
	if v != nil {
		_u.SetIndexedAt(*v)
	}
	return _u
}

// ClearIndexedAt clears the value of the "indexed_at" field.
func (_u *DocumentChunkUpdateOne) ClearIndexedAt() *DocumentChunkUpdateOne {
	_u.mutation.ClearIndexedAt()
	return _u
}

// SetDocumentID sets the "document" edge to the Document entity by ID.
func (_u *DocumentChunkUpdateOne) SetDocumentID(id int) *DocumentChunkUpdateOne {
	_u.mutation.SetDocumentID(id)
	return _u
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *DocumentChunkUpdateOne) SetDocument(v *Document) *DocumentChunkUpdateOne {
	return _u.SetDocumentID(v.ID)
}

// Mutation returns the DocumentChunkMutation object of the builder.
func (_u *DocumentChunkUpdateOne) Mutation() *DocumentChunkMutation {
	return _u.mutation
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *DocumentChunkUpdateOne) ClearDocument() *DocumentChunkUpdateOne {
	_u.mutation.ClearDocument()
	return _u
}

// Where appends a list predicates to the DocumentChunkUpdate builder.
func (_u *DocumentChunkUpdateOne) Where(ps ...predicate.DocumentChunk) *DocumentChunkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DocumentChunkUpdateOne) Select(field string, fields ...string) *DocumentChunkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DocumentChunk entity.
func (_u *DocumentChunkUpdateOne) Save(ctx context.Context) (*DocumentChunk, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentChunkUpdateOne) SaveX(ctx context.Context) *DocumentChunk {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DocumentChunkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentChunkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentChunkUpdateOne) check() error {
	if v, ok := _u.mutation.VectorStatus(); ok {
		if err := documentchunk.VectorStatusValidator(v); err != nil {
			return &ValidationError{Name: "vector_status", err: fmt.Errorf(`ent: validator failed for field "DocumentChunk.vector_status": %w`, err)}
		}
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DocumentChunk.document"`)
	}
	return nil
}

func (_u *DocumentChunkUpdateOne) sqlSave(ctx context.Context) (_node *DocumentChunk, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(documentchunk.Table, documentchunk.Columns, sqlgraph.NewFieldSpec(documentchunk.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DocumentChunk.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, documentchunk.FieldID)
		for _, f := range fields {
			if !documentchunk.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != documentchunk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(documentchunk.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeadingPath(); ok {
		_spec.SetField(documentchunk.FieldHeadingPath, field.TypeString, value)
	}
	if _u.mutation.HeadingPathCleared() {
		_spec.ClearField(documentchunk.FieldHeadingPath, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(documentchunk.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(documentchunk.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartLine(); ok {
		_spec.SetField(documentchunk.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartLine(); ok {
		_spec.AddField(documentchunk.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EndLine(); ok {
		_spec.SetField(documentchunk.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndLine(); ok {
		_spec.AddField(documentchunk.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CharacterCount(); ok {
		_spec.SetField(documentchunk.FieldCharacterCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCharacterCount(); ok {
		_spec.AddField(documentchunk.FieldCharacterCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EmbeddingModel(); ok {
		_spec.SetField(documentchunk.FieldEmbeddingModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.VectorStatus(); ok {
		_spec.SetField(documentchunk.FieldVectorStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IndexedAt(); ok {
		_spec.SetField(documentchunk.FieldIndexedAt, field.TypeTime, value)
	}
	if _u.mutation.IndexedAtCleared() {
		_spec.ClearField(documentchunk.FieldIndexedAt, field.TypeTime)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentchunk.DocumentTable,
			Columns: []string{documentchunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentchunk.DocumentTable,
			Columns: []string{documentchunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DocumentChunk{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{documentchunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
