// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eino-quickstart/ent/document"
	"eino-quickstart/ent/documentchunk"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DocumentChunkCreate is the builder for creating a DocumentChunk entity.
type DocumentChunkCreate struct {
	config
	mutation *DocumentChunkMutation
	hooks    []Hook
}

// SetChunkIndex sets the "chunk_index" field.
func (_c *DocumentChunkCreate) SetChunkIndex(v int) *DocumentChunkCreate {
	_c.mutation.SetChunkIndex(v)
	return _c
}

// SetCitationID sets the "citation_id" field.
func (_c *DocumentChunkCreate) SetCitationID(v string) *DocumentChunkCreate {
	_c.mutation.SetCitationID(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *DocumentChunkCreate) SetContent(v string) *DocumentChunkCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetHeadingPath sets the "heading_path" field.
func (_c *DocumentChunkCreate) SetHeadingPath(v string) *DocumentChunkCreate {
	_c.mutation.SetHeadingPath(v)
	return _c
}

// SetNillableHeadingPath sets the "heading_path" field if the given value is not nil.
func (_c *DocumentChunkCreate) SetNillableHeadingPath(v *string) *DocumentChunkCreate {
	if v != nil {
		_c.SetHeadingPath(*v)
	}
	return _c
}

// SetStartLine sets the "start_line" field.
func (_c *DocumentChunkCreate) SetStartLine(v int) *DocumentChunkCreate {
	_c.mutation.SetStartLine(v)
	return _c
}

// SetEndLine sets the "end_line" field.
func (_c *DocumentChunkCreate) SetEndLine(v int) *DocumentChunkCreate {
	_c.mutation.SetEndLine(v)
	return _c
}

// SetCharacterCount sets the "character_count" field.
func (_c *DocumentChunkCreate) SetCharacterCount(v int) *DocumentChunkCreate {
	_c.mutation.SetCharacterCount(v)
	return _c
}

// SetEmbeddingModel sets the "embedding_model" field.
func (_c *DocumentChunkCreate) SetEmbeddingModel(v string) *DocumentChunkCreate {
	_c.mutation.SetEmbeddingModel(v)
	return _c
}

// SetVectorStatus sets the "vector_status" field.
func (_c *DocumentChunkCreate) SetVectorStatus(v documentchunk.VectorStatus) *DocumentChunkCreate {
	_c.mutation.SetVectorStatus(v)
	return _c
}

// SetNillableVectorStatus sets the "vector_status" field if the given value is not nil.
func (_c *DocumentChunkCreate) SetNillableVectorStatus(v *documentchunk.VectorStatus) *DocumentChunkCreate {
	if v != nil {
		_c.SetVectorStatus(*v)
	}
	return _c
}

// SetIndexedAt sets the "indexed_at" field.
func (_c *DocumentChunkCreate) SetIndexedAt(v time.Time) *DocumentChunkCreate {
	_c.mutation.SetIndexedAt(v)
	return _c
}

// SetNillableIndexedAt sets the "indexed_at" field if the given value is not nil.
func (_c *DocumentChunkCreate) SetNillableIndexedAt(v *time.Time) *DocumentChunkCreate {
	if v != nil {
		_c.SetIndexedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DocumentChunkCreate) SetCreatedAt(v time.Time) *DocumentChunkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DocumentChunkCreate) SetNillableCreatedAt(v *time.Time) *DocumentChunkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetDocumentID sets the "document" edge to the Document entity by ID.
func (_c *DocumentChunkCreate) SetDocumentID(id int) *DocumentChunkCreate {
	_c.mutation.SetDocumentID(id)
	return _c
}

// SetDocument sets the "document" edge to the Document entity.
func (_c *DocumentChunkCreate) SetDocument(v *Document) *DocumentChunkCreate {
	return _c.SetDocumentID(v.ID)
}

// Mutation returns the DocumentChunkMutation object of the builder.
func (_c *DocumentChunkCreate) Mutation() *DocumentChunkMutation {
	return _c.mutation
}

// Save creates the DocumentChunk in the database.
func (_c *DocumentChunkCreate) Save(ctx context.Context) (*DocumentChunk, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DocumentChunkCreate) SaveX(ctx context.Context) *DocumentChunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentChunkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentChunkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DocumentChunkCreate) defaults() {
	if _, ok := _c.mutation.VectorStatus(); !ok {
		v := documentchunk.DefaultVectorStatus
		_c.mutation.SetVectorStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := documentchunk.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DocumentChunkCreate) check() error {
	if _, ok := _c.mutation.ChunkIndex(); !ok {
		return &ValidationError{Name: "chunk_index", err: errors.New(`ent: missing required field "DocumentChunk.chunk_index"`)}
	}
	if _, ok := _c.mutation.CitationID(); !ok {
		return &ValidationError{Name: "citation_id", err: errors.New(`ent: missing required field "DocumentChunk.citation_id"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "DocumentChunk.content"`)}
	}
	if _, ok := _c.mutation.StartLine(); !ok {
		return &ValidationError{Name: "start_line", err: errors.New(`ent: missing required field "DocumentChunk.start_line"`)}
	}
	if _, ok := _c.mutation.EndLine(); !ok {
		return &ValidationError{Name: "end_line", err: errors.New(`ent: missing required field "DocumentChunk.end_line"`)}
	}
	if _, ok := _c.mutation.CharacterCount(); !ok {
		return &ValidationError{Name: "character_count", err: errors.New(`ent: missing required field "DocumentChunk.character_count"`)}
	}
	if _, ok := _c.mutation.EmbeddingModel(); !ok {
		return &ValidationError{Name: "embedding_model", err: errors.New(`ent: missing required field "DocumentChunk.embedding_model"`)}
	}
	if _, ok := _c.mutation.VectorStatus(); !ok {
		return &ValidationError{Name: "vector_status", err: errors.New(`ent: missing required field "DocumentChunk.vector_status"`)}
	}
	if v, ok := _c.mutation.VectorStatus(); ok {
		if err := documentchunk.VectorStatusValidator(v); err != nil {
			return &ValidationError{Name: "vector_status", err: fmt.Errorf(`ent: validator failed for field "DocumentChunk.vector_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DocumentChunk.created_at"`)}
	}
	if len(_c.mutation.DocumentIDs()) == 0 {
		return &ValidationError{Name: "document", err: errors.New(`ent: missing required edge "DocumentChunk.document"`)}
	}
	return nil
}

func (_c *DocumentChunkCreate) sqlSave(ctx context.Context) (*DocumentChunk, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DocumentChunkCreate) createSpec() (*DocumentChunk, *sqlgraph.CreateSpec) {
	var (
		_node = &DocumentChunk{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(documentchunk.Table, sqlgraph.NewFieldSpec(documentchunk.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ChunkIndex(); ok {
		_spec.SetField(documentchunk.FieldChunkIndex, field.TypeInt, value)
		_node.ChunkIndex = value
	}
	if value, ok := _c.mutation.CitationID(); ok {
		_spec.SetField(documentchunk.FieldCitationID, field.TypeString, value)
		_node.CitationID = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(documentchunk.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.HeadingPath(); ok {
		_spec.SetField(documentchunk.FieldHeadingPath, field.TypeString, value)
		_node.HeadingPath = &value
	}
	if value, ok := _c.mutation.StartLine(); ok {
		_spec.SetField(documentchunk.FieldStartLine, field.TypeInt, value)
		_node.StartLine = value
	}
	if value, ok := _c.mutation.EndLine(); ok {
		_spec.SetField(documentchunk.FieldEndLine, field.TypeInt, value)
		_node.EndLine = value
	}
	if value, ok := _c.mutation.CharacterCount(); ok {
		_spec.SetField(documentchunk.FieldCharacterCount, field.TypeInt, value)
		_node.CharacterCount = value
	}
	if value, ok := _c.mutation.EmbeddingModel(); ok {
		_spec.SetField(documentchunk.FieldEmbeddingModel, field.TypeString, value)
		_node.EmbeddingModel = value
	}
	if value, ok := _c.mutation.VectorStatus(); ok {
		_spec.SetField(documentchunk.FieldVectorStatus, field.TypeEnum, value)
		_node.VectorStatus = value
	}
	if value, ok := _c.mutation.IndexedAt(); ok {
		_spec.SetField(documentchunk.FieldIndexedAt, field.TypeTime, value)
		_node.IndexedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(documentchunk.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentchunk.DocumentTable,
			Columns: []string{documentchunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.document_chunks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DocumentChunkCreateBulk is the builder for creating many DocumentChunk entities in bulk.
type DocumentChunkCreateBulk struct {
	config
	err      error
	builders []*DocumentChunkCreate
}

// Save creates the DocumentChunk entities in the database.
func (_c *DocumentChunkCreateBulk) Save(ctx context.Context) ([]*DocumentChunk, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DocumentChunk, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocumentChunkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DocumentChunkCreateBulk) SaveX(ctx context.Context) []*DocumentChunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentChunkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentChunkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
