// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eino-quickstart/ent/document"
	"eino-quickstart/ent/knowledgebase"
	"eino-quickstart/ent/knowledgefolder"
	"eino-quickstart/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KnowledgeBaseUpdate is the builder for updating KnowledgeBase entities.
type KnowledgeBaseUpdate struct {
	config
	hooks    []Hook
	mutation *KnowledgeBaseMutation
}

// Where appends a list predicates to the KnowledgeBaseUpdate builder.
func (_u *KnowledgeBaseUpdate) Where(ps ...predicate.KnowledgeBase) *KnowledgeBaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *KnowledgeBaseUpdate) SetName(v string) *KnowledgeBaseUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableName(v *string) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *KnowledgeBaseUpdate) SetDescription(v string) *KnowledgeBaseUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableDescription(v *string) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *KnowledgeBaseUpdate) ClearDescription() *KnowledgeBaseUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetOwnerSubject sets the "owner_subject" field.
func (_u *KnowledgeBaseUpdate) SetOwnerSubject(v string) *KnowledgeBaseUpdate {
	_u.mutation.SetOwnerSubject(v)
	return _u
}

// SetNillableOwnerSubject sets the "owner_subject" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableOwnerSubject(v *string) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetOwnerSubject(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *KnowledgeBaseUpdate) SetVisibility(v knowledgebase.Visibility) *KnowledgeBaseUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableVisibility(v *knowledgebase.Visibility) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *KnowledgeBaseUpdate) SetStatus(v knowledgebase.Status) *KnowledgeBaseUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *KnowledgeBaseUpdate) SetNillableStatus(v *knowledgebase.Status) *KnowledgeBaseUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KnowledgeBaseUpdate) SetUpdatedAt(v time.Time) *KnowledgeBaseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddFolderIDs adds the "folders" edge to the KnowledgeFolder entity by IDs.
func (_u *KnowledgeBaseUpdate) AddFolderIDs(ids ...int) *KnowledgeBaseUpdate {
	_u.mutation.AddFolderIDs(ids...)
	return _u
}

// AddFolders adds the "folders" edges to the KnowledgeFolder entity.
func (_u *KnowledgeBaseUpdate) AddFolders(v ...*KnowledgeFolder) *KnowledgeBaseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFolderIDs(ids...)
}

// AddDocumentIDs adds the "documents" edge to the Document entity by IDs.
func (_u *KnowledgeBaseUpdate) AddDocumentIDs(ids ...int) *KnowledgeBaseUpdate {
	_u.mutation.AddDocumentIDs(ids...)
	return _u
}

// AddDocuments adds the "documents" edges to the Document entity.
func (_u *KnowledgeBaseUpdate) AddDocuments(v ...*Document) *KnowledgeBaseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentIDs(ids...)
}

// Mutation returns the KnowledgeBaseMutation object of the builder.
func (_u *KnowledgeBaseUpdate) Mutation() *KnowledgeBaseMutation {
	return _u.mutation
}

// ClearFolders clears all "folders" edges to the KnowledgeFolder entity.
func (_u *KnowledgeBaseUpdate) ClearFolders() *KnowledgeBaseUpdate {
	_u.mutation.ClearFolders()
	return _u
}

// RemoveFolderIDs removes the "folders" edge to KnowledgeFolder entities by IDs.
func (_u *KnowledgeBaseUpdate) RemoveFolderIDs(ids ...int) *KnowledgeBaseUpdate {
	_u.mutation.RemoveFolderIDs(ids...)
	return _u
}

// RemoveFolders removes "folders" edges to KnowledgeFolder entities.
func (_u *KnowledgeBaseUpdate) RemoveFolders(v ...*KnowledgeFolder) *KnowledgeBaseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFolderIDs(ids...)
}

// ClearDocuments clears all "documents" edges to the Document entity.
func (_u *KnowledgeBaseUpdate) ClearDocuments() *KnowledgeBaseUpdate {
	_u.mutation.ClearDocuments()
	return _u
}

// RemoveDocumentIDs removes the "documents" edge to Document entities by IDs.
func (_u *KnowledgeBaseUpdate) RemoveDocumentIDs(ids ...int) *KnowledgeBaseUpdate {
	_u.mutation.RemoveDocumentIDs(ids...)
	return _u
}

// RemoveDocuments removes "documents" edges to Document entities.
func (_u *KnowledgeBaseUpdate) RemoveDocuments(v ...*Document) *KnowledgeBaseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KnowledgeBaseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeBaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KnowledgeBaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeBaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KnowledgeBaseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := knowledgebase.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeBaseUpdate) check() error {
	if v, ok := _u.mutation.Visibility(); ok {
		if err := knowledgebase.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.visibility": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := knowledgebase.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.status": %w`, err)}
		}
	}
	return nil
}

func (_u *KnowledgeBaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgebase.Table, knowledgebase.Columns, sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(knowledgebase.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(knowledgebase.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(knowledgebase.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerSubject(); ok {
		_spec.SetField(knowledgebase.FieldOwnerSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(knowledgebase.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(knowledgebase.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgebase.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FoldersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgebase.FoldersTable,
			Columns: []string{knowledgebase.FoldersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFoldersIDs(); len(nodes) > 0 && !_u.mutation.FoldersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgebase.FoldersTable,
			Columns: []string{knowledgebase.FoldersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FoldersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgebase.FoldersTable,
			Columns: []string{knowledgebase.FoldersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgebase.DocumentsTable,
			Columns: []string{knowledgebase.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentsIDs(); len(nodes) > 0 && !_u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgebase.DocumentsTable,
			Columns: []string{knowledgebase.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgebase.DocumentsTable,
			Columns: []string{knowledgebase.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgebase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KnowledgeBaseUpdateOne is the builder for updating a single KnowledgeBase entity.
type KnowledgeBaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KnowledgeBaseMutation
}

// SetName sets the "name" field.
func (_u *KnowledgeBaseUpdateOne) SetName(v string) *KnowledgeBaseUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableName(v *string) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *KnowledgeBaseUpdateOne) SetDescription(v string) *KnowledgeBaseUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableDescription(v *string) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *KnowledgeBaseUpdateOne) ClearDescription() *KnowledgeBaseUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetOwnerSubject sets the "owner_subject" field.
func (_u *KnowledgeBaseUpdateOne) SetOwnerSubject(v string) *KnowledgeBaseUpdateOne {
	_u.mutation.SetOwnerSubject(v)
	return _u
}

// SetNillableOwnerSubject sets the "owner_subject" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableOwnerSubject(v *string) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetOwnerSubject(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *KnowledgeBaseUpdateOne) SetVisibility(v knowledgebase.Visibility) *KnowledgeBaseUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableVisibility(v *knowledgebase.Visibility) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *KnowledgeBaseUpdateOne) SetStatus(v knowledgebase.Status) *KnowledgeBaseUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *KnowledgeBaseUpdateOne) SetNillableStatus(v *knowledgebase.Status) *KnowledgeBaseUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KnowledgeBaseUpdateOne) SetUpdatedAt(v time.Time) *KnowledgeBaseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddFolderIDs adds the "folders" edge to the KnowledgeFolder entity by IDs.
func (_u *KnowledgeBaseUpdateOne) AddFolderIDs(ids ...int) *KnowledgeBaseUpdateOne {
	_u.mutation.AddFolderIDs(ids...)
	return _u
}

// AddFolders adds the "folders" edges to the KnowledgeFolder entity.
func (_u *KnowledgeBaseUpdateOne) AddFolders(v ...*KnowledgeFolder) *KnowledgeBaseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFolderIDs(ids...)
}

// AddDocumentIDs adds the "documents" edge to the Document entity by IDs.
func (_u *KnowledgeBaseUpdateOne) AddDocumentIDs(ids ...int) *KnowledgeBaseUpdateOne {
	_u.mutation.AddDocumentIDs(ids...)
	return _u
}

// AddDocuments adds the "documents" edges to the Document entity.
func (_u *KnowledgeBaseUpdateOne) AddDocuments(v ...*Document) *KnowledgeBaseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentIDs(ids...)
}

// Mutation returns the KnowledgeBaseMutation object of the builder.
func (_u *KnowledgeBaseUpdateOne) Mutation() *KnowledgeBaseMutation {
	return _u.mutation
}

// ClearFolders clears all "folders" edges to the KnowledgeFolder entity.
func (_u *KnowledgeBaseUpdateOne) ClearFolders() *KnowledgeBaseUpdateOne {
	_u.mutation.ClearFolders()
	return _u
}

// RemoveFolderIDs removes the "folders" edge to KnowledgeFolder entities by IDs.
func (_u *KnowledgeBaseUpdateOne) RemoveFolderIDs(ids ...int) *KnowledgeBaseUpdateOne {
	_u.mutation.RemoveFolderIDs(ids...)
	return _u
}

// RemoveFolders removes "folders" edges to KnowledgeFolder entities.
func (_u *KnowledgeBaseUpdateOne) RemoveFolders(v ...*KnowledgeFolder) *KnowledgeBaseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFolderIDs(ids...)
}

// ClearDocuments clears all "documents" edges to the Document entity.
func (_u *KnowledgeBaseUpdateOne) ClearDocuments() *KnowledgeBaseUpdateOne {
	_u.mutation.ClearDocuments()
	return _u
}

// RemoveDocumentIDs removes the "documents" edge to Document entities by IDs.
func (_u *KnowledgeBaseUpdateOne) RemoveDocumentIDs(ids ...int) *KnowledgeBaseUpdateOne {
	_u.mutation.RemoveDocumentIDs(ids...)
	return _u
}

// RemoveDocuments removes "documents" edges to Document entities.
func (_u *KnowledgeBaseUpdateOne) RemoveDocuments(v ...*Document) *KnowledgeBaseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentIDs(ids...)
}

// Where appends a list predicates to the KnowledgeBaseUpdate builder.
func (_u *KnowledgeBaseUpdateOne) Where(ps ...predicate.KnowledgeBase) *KnowledgeBaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KnowledgeBaseUpdateOne) Select(field string, fields ...string) *KnowledgeBaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KnowledgeBase entity.
func (_u *KnowledgeBaseUpdateOne) Save(ctx context.Context) (*KnowledgeBase, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeBaseUpdateOne) SaveX(ctx context.Context) *KnowledgeBase {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KnowledgeBaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeBaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KnowledgeBaseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := knowledgebase.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeBaseUpdateOne) check() error {
	if v, ok := _u.mutation.Visibility(); ok {
		if err := knowledgebase.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.visibility": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := knowledgebase.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "KnowledgeBase.status": %w`, err)}
		}
	}
	return nil
}

func (_u *KnowledgeBaseUpdateOne) sqlSave(ctx context.Context) (_node *KnowledgeBase, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgebase.Table, knowledgebase.Columns, sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KnowledgeBase.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, knowledgebase.FieldID)
		for _, f := range fields {
			if !knowledgebase.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != knowledgebase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(knowledgebase.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(knowledgebase.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(knowledgebase.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerSubject(); ok {
		_spec.SetField(knowledgebase.FieldOwnerSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(knowledgebase.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(knowledgebase.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgebase.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FoldersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgebase.FoldersTable,
			Columns: []string{knowledgebase.FoldersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFoldersIDs(); len(nodes) > 0 && !_u.mutation.FoldersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgebase.FoldersTable,
			Columns: []string{knowledgebase.FoldersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FoldersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgebase.FoldersTable,
			Columns: []string{knowledgebase.FoldersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgebase.DocumentsTable,
			Columns: []string{knowledgebase.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentsIDs(); len(nodes) > 0 && !_u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgebase.DocumentsTable,
			Columns: []string{knowledgebase.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgebase.DocumentsTable,
			Columns: []string{knowledgebase.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &KnowledgeBase{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgebase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
