// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eino-quickstart/ent/document"
	"eino-quickstart/ent/knowledgebase"
	"eino-quickstart/ent/knowledgefolder"
	"eino-quickstart/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KnowledgeFolderUpdate is the builder for updating KnowledgeFolder entities.
type KnowledgeFolderUpdate struct {
	config
	hooks    []Hook
	mutation *KnowledgeFolderMutation
}

// Where appends a list predicates to the KnowledgeFolderUpdate builder.
func (_u *KnowledgeFolderUpdate) Where(ps ...predicate.KnowledgeFolder) *KnowledgeFolderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *KnowledgeFolderUpdate) SetName(v string) *KnowledgeFolderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *KnowledgeFolderUpdate) SetNillableName(v *string) *KnowledgeFolderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *KnowledgeFolderUpdate) SetPath(v string) *KnowledgeFolderUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *KnowledgeFolderUpdate) SetNillablePath(v *string) *KnowledgeFolderUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *KnowledgeFolderUpdate) SetSort(v int) *KnowledgeFolderUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *KnowledgeFolderUpdate) SetNillableSort(v *int) *KnowledgeFolderUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *KnowledgeFolderUpdate) AddSort(v int) *KnowledgeFolderUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *KnowledgeFolderUpdate) SetParentID(v int) *KnowledgeFolderUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *KnowledgeFolderUpdate) SetNillableParentID(v *int) *KnowledgeFolderUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *KnowledgeFolderUpdate) ClearParentID() *KnowledgeFolderUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KnowledgeFolderUpdate) SetUpdatedAt(v time.Time) *KnowledgeFolderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKnowledgeBaseID sets the "knowledge_base" edge to the KnowledgeBase entity by ID.
func (_u *KnowledgeFolderUpdate) SetKnowledgeBaseID(id int) *KnowledgeFolderUpdate {
	_u.mutation.SetKnowledgeBaseID(id)
	return _u
}

// SetKnowledgeBase sets the "knowledge_base" edge to the KnowledgeBase entity.
func (_u *KnowledgeFolderUpdate) SetKnowledgeBase(v *KnowledgeBase) *KnowledgeFolderUpdate {
	return _u.SetKnowledgeBaseID(v.ID)
}

// SetParent sets the "parent" edge to the KnowledgeFolder entity.
func (_u *KnowledgeFolderUpdate) SetParent(v *KnowledgeFolder) *KnowledgeFolderUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the KnowledgeFolder entity by IDs.
func (_u *KnowledgeFolderUpdate) AddChildIDs(ids ...int) *KnowledgeFolderUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the KnowledgeFolder entity.
func (_u *KnowledgeFolderUpdate) AddChildren(v ...*KnowledgeFolder) *KnowledgeFolderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddDocumentIDs adds the "documents" edge to the Document entity by IDs.
func (_u *KnowledgeFolderUpdate) AddDocumentIDs(ids ...int) *KnowledgeFolderUpdate {
	_u.mutation.AddDocumentIDs(ids...)
	return _u
}

// AddDocuments adds the "documents" edges to the Document entity.
func (_u *KnowledgeFolderUpdate) AddDocuments(v ...*Document) *KnowledgeFolderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentIDs(ids...)
}

// Mutation returns the KnowledgeFolderMutation object of the builder.
func (_u *KnowledgeFolderUpdate) Mutation() *KnowledgeFolderMutation {
	return _u.mutation
}

// ClearKnowledgeBase clears the "knowledge_base" edge to the KnowledgeBase entity.
func (_u *KnowledgeFolderUpdate) ClearKnowledgeBase() *KnowledgeFolderUpdate {
	_u.mutation.ClearKnowledgeBase()
	return _u
}

// ClearParent clears the "parent" edge to the KnowledgeFolder entity.
func (_u *KnowledgeFolderUpdate) ClearParent() *KnowledgeFolderUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the KnowledgeFolder entity.
func (_u *KnowledgeFolderUpdate) ClearChildren() *KnowledgeFolderUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to KnowledgeFolder entities by IDs.
func (_u *KnowledgeFolderUpdate) RemoveChildIDs(ids ...int) *KnowledgeFolderUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to KnowledgeFolder entities.
func (_u *KnowledgeFolderUpdate) RemoveChildren(v ...*KnowledgeFolder) *KnowledgeFolderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearDocuments clears all "documents" edges to the Document entity.
func (_u *KnowledgeFolderUpdate) ClearDocuments() *KnowledgeFolderUpdate {
	_u.mutation.ClearDocuments()
	return _u
}

// RemoveDocumentIDs removes the "documents" edge to Document entities by IDs.
func (_u *KnowledgeFolderUpdate) RemoveDocumentIDs(ids ...int) *KnowledgeFolderUpdate {
	_u.mutation.RemoveDocumentIDs(ids...)
	return _u
}

// RemoveDocuments removes "documents" edges to Document entities.
func (_u *KnowledgeFolderUpdate) RemoveDocuments(v ...*Document) *KnowledgeFolderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KnowledgeFolderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeFolderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KnowledgeFolderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeFolderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KnowledgeFolderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := knowledgefolder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeFolderUpdate) check() error {
	if _u.mutation.KnowledgeBaseCleared() && len(_u.mutation.KnowledgeBaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "KnowledgeFolder.knowledge_base"`)
	}
	return nil
}

func (_u *KnowledgeFolderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgefolder.Table, knowledgefolder.Columns, sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(knowledgefolder.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(knowledgefolder.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(knowledgefolder.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(knowledgefolder.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgefolder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.KnowledgeBaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefolder.KnowledgeBaseTable,
			Columns: []string{knowledgefolder.KnowledgeBaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KnowledgeBaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefolder.KnowledgeBaseTable,
			Columns: []string{knowledgefolder.KnowledgeBaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefolder.ParentTable,
			Columns: []string{knowledgefolder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefolder.ParentTable,
			Columns: []string{knowledgefolder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgefolder.ChildrenTable,
			Columns: []string{knowledgefolder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgefolder.ChildrenTable,
			Columns: []string{knowledgefolder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgefolder.ChildrenTable,
			Columns: []string{knowledgefolder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgefolder.DocumentsTable,
			Columns: []string{knowledgefolder.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentsIDs(); len(nodes) > 0 && !_u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgefolder.DocumentsTable,
			Columns: []string{knowledgefolder.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgefolder.DocumentsTable,
			Columns: []string{knowledgefolder.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgefolder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KnowledgeFolderUpdateOne is the builder for updating a single KnowledgeFolder entity.
type KnowledgeFolderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KnowledgeFolderMutation
}

// SetName sets the "name" field.
func (_u *KnowledgeFolderUpdateOne) SetName(v string) *KnowledgeFolderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *KnowledgeFolderUpdateOne) SetNillableName(v *string) *KnowledgeFolderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *KnowledgeFolderUpdateOne) SetPath(v string) *KnowledgeFolderUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *KnowledgeFolderUpdateOne) SetNillablePath(v *string) *KnowledgeFolderUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *KnowledgeFolderUpdateOne) SetSort(v int) *KnowledgeFolderUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *KnowledgeFolderUpdateOne) SetNillableSort(v *int) *KnowledgeFolderUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *KnowledgeFolderUpdateOne) AddSort(v int) *KnowledgeFolderUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *KnowledgeFolderUpdateOne) SetParentID(v int) *KnowledgeFolderUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *KnowledgeFolderUpdateOne) SetNillableParentID(v *int) *KnowledgeFolderUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *KnowledgeFolderUpdateOne) ClearParentID() *KnowledgeFolderUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KnowledgeFolderUpdateOne) SetUpdatedAt(v time.Time) *KnowledgeFolderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKnowledgeBaseID sets the "knowledge_base" edge to the KnowledgeBase entity by ID.
func (_u *KnowledgeFolderUpdateOne) SetKnowledgeBaseID(id int) *KnowledgeFolderUpdateOne {
	_u.mutation.SetKnowledgeBaseID(id)
	return _u
}

// SetKnowledgeBase sets the "knowledge_base" edge to the KnowledgeBase entity.
func (_u *KnowledgeFolderUpdateOne) SetKnowledgeBase(v *KnowledgeBase) *KnowledgeFolderUpdateOne {
	return _u.SetKnowledgeBaseID(v.ID)
}

// SetParent sets the "parent" edge to the KnowledgeFolder entity.
func (_u *KnowledgeFolderUpdateOne) SetParent(v *KnowledgeFolder) *KnowledgeFolderUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the KnowledgeFolder entity by IDs.
func (_u *KnowledgeFolderUpdateOne) AddChildIDs(ids ...int) *KnowledgeFolderUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the KnowledgeFolder entity.
func (_u *KnowledgeFolderUpdateOne) AddChildren(v ...*KnowledgeFolder) *KnowledgeFolderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddDocumentIDs adds the "documents" edge to the Document entity by IDs.
func (_u *KnowledgeFolderUpdateOne) AddDocumentIDs(ids ...int) *KnowledgeFolderUpdateOne {
	_u.mutation.AddDocumentIDs(ids...)
	return _u
}

// AddDocuments adds the "documents" edges to the Document entity.
func (_u *KnowledgeFolderUpdateOne) AddDocuments(v ...*Document) *KnowledgeFolderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentIDs(ids...)
}

// Mutation returns the KnowledgeFolderMutation object of the builder.
func (_u *KnowledgeFolderUpdateOne) Mutation() *KnowledgeFolderMutation {
	return _u.mutation
}

// ClearKnowledgeBase clears the "knowledge_base" edge to the KnowledgeBase entity.
func (_u *KnowledgeFolderUpdateOne) ClearKnowledgeBase() *KnowledgeFolderUpdateOne {
	_u.mutation.ClearKnowledgeBase()
	return _u
}

// ClearParent clears the "parent" edge to the KnowledgeFolder entity.
func (_u *KnowledgeFolderUpdateOne) ClearParent() *KnowledgeFolderUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the KnowledgeFolder entity.
func (_u *KnowledgeFolderUpdateOne) ClearChildren() *KnowledgeFolderUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to KnowledgeFolder entities by IDs.
func (_u *KnowledgeFolderUpdateOne) RemoveChildIDs(ids ...int) *KnowledgeFolderUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to KnowledgeFolder entities.
func (_u *KnowledgeFolderUpdateOne) RemoveChildren(v ...*KnowledgeFolder) *KnowledgeFolderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearDocuments clears all "documents" edges to the Document entity.
func (_u *KnowledgeFolderUpdateOne) ClearDocuments() *KnowledgeFolderUpdateOne {
	_u.mutation.ClearDocuments()
	return _u
}

// RemoveDocumentIDs removes the "documents" edge to Document entities by IDs.
func (_u *KnowledgeFolderUpdateOne) RemoveDocumentIDs(ids ...int) *KnowledgeFolderUpdateOne {
	_u.mutation.RemoveDocumentIDs(ids...)
	return _u
}

// RemoveDocuments removes "documents" edges to Document entities.
func (_u *KnowledgeFolderUpdateOne) RemoveDocuments(v ...*Document) *KnowledgeFolderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentIDs(ids...)
}

// Where appends a list predicates to the KnowledgeFolderUpdate builder.
func (_u *KnowledgeFolderUpdateOne) Where(ps ...predicate.KnowledgeFolder) *KnowledgeFolderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KnowledgeFolderUpdateOne) Select(field string, fields ...string) *KnowledgeFolderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KnowledgeFolder entity.
func (_u *KnowledgeFolderUpdateOne) Save(ctx context.Context) (*KnowledgeFolder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeFolderUpdateOne) SaveX(ctx context.Context) *KnowledgeFolder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KnowledgeFolderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeFolderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KnowledgeFolderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := knowledgefolder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeFolderUpdateOne) check() error {
	if _u.mutation.KnowledgeBaseCleared() && len(_u.mutation.KnowledgeBaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "KnowledgeFolder.knowledge_base"`)
	}
	return nil
}

func (_u *KnowledgeFolderUpdateOne) sqlSave(ctx context.Context) (_node *KnowledgeFolder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgefolder.Table, knowledgefolder.Columns, sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KnowledgeFolder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, knowledgefolder.FieldID)
		for _, f := range fields {
			if !knowledgefolder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != knowledgefolder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(knowledgefolder.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(knowledgefolder.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(knowledgefolder.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(knowledgefolder.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgefolder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.KnowledgeBaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefolder.KnowledgeBaseTable,
			Columns: []string{knowledgefolder.KnowledgeBaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KnowledgeBaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefolder.KnowledgeBaseTable,
			Columns: []string{knowledgefolder.KnowledgeBaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgebase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefolder.ParentTable,
			Columns: []string{knowledgefolder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefolder.ParentTable,
			Columns: []string{knowledgefolder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgefolder.ChildrenTable,
			Columns: []string{knowledgefolder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgefolder.ChildrenTable,
			Columns: []string{knowledgefolder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgefolder.ChildrenTable,
			Columns: []string{knowledgefolder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgefolder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgefolder.DocumentsTable,
			Columns: []string{knowledgefolder.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentsIDs(); len(nodes) > 0 && !_u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgefolder.DocumentsTable,
			Columns: []string{knowledgefolder.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgefolder.DocumentsTable,
			Columns: []string{knowledgefolder.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &KnowledgeFolder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgefolder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
