// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"eino-quickstart/ent/agentrun"
	"eino-quickstart/ent/approval"
	"eino-quickstart/ent/auditevent"
	"eino-quickstart/ent/chatturn"
	"eino-quickstart/ent/checkpoint"
	"eino-quickstart/ent/document"
	"eino-quickstart/ent/documentchunk"
	"eino-quickstart/ent/knowledgebase"
	"eino-quickstart/ent/knowledgefolder"
	"eino-quickstart/ent/knowledgeindex"
	"eino-quickstart/ent/session"
	"eino-quickstart/ent/sessionmessage"
	"eino-quickstart/ent/vectoroutbox"
	"fmt"
)

const errInvalidPage = "INVALID_PAGE"

const (
	listField     = "list"
	pageNumField  = "pageNum"
	pageSizeField = "pageSize"
)

type PageDetails struct {
	Page  uint64 `json:"page"`
	Size  uint64 `json:"size"`
	Total uint64 `json:"total"`
}

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

const errInvalidPagination = "INVALID_PAGINATION"

type AgentRunPager struct {
	Order  agentrun.OrderOption
	Filter func(*AgentRunQuery) (*AgentRunQuery, error)
}

// AgentRunPaginateOption enables pagination customization.
type AgentRunPaginateOption func(*AgentRunPager)

// DefaultAgentRunOrder is the default ordering of AgentRun.
var DefaultAgentRunOrder = Desc(agentrun.FieldID)

func newAgentRunPager(opts []AgentRunPaginateOption) (*AgentRunPager, error) {
	pager := &AgentRunPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultAgentRunOrder
	}
	return pager, nil
}

func (p *AgentRunPager) ApplyFilter(query *AgentRunQuery) (*AgentRunQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// AgentRunPageList is AgentRun PageList result.
type AgentRunPageList struct {
	List        []*AgentRun  `json:"list"`
	PageDetails *PageDetails `json:"pageDetails"`
}

func (_m *AgentRunQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...AgentRunPaginateOption,
) (*AgentRunPageList, error) {

	pager, err := newAgentRunPager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &AgentRunPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := _m.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		_m = _m.Order(DefaultAgentRunOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}

type ApprovalPager struct {
	Order  approval.OrderOption
	Filter func(*ApprovalQuery) (*ApprovalQuery, error)
}

// ApprovalPaginateOption enables pagination customization.
type ApprovalPaginateOption func(*ApprovalPager)

// DefaultApprovalOrder is the default ordering of Approval.
var DefaultApprovalOrder = Desc(approval.FieldID)

func newApprovalPager(opts []ApprovalPaginateOption) (*ApprovalPager, error) {
	pager := &ApprovalPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultApprovalOrder
	}
	return pager, nil
}

func (p *ApprovalPager) ApplyFilter(query *ApprovalQuery) (*ApprovalQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// ApprovalPageList is Approval PageList result.
type ApprovalPageList struct {
	List        []*Approval  `json:"list"`
	PageDetails *PageDetails `json:"pageDetails"`
}

func (_m *ApprovalQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...ApprovalPaginateOption,
) (*ApprovalPageList, error) {

	pager, err := newApprovalPager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &ApprovalPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := _m.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		_m = _m.Order(DefaultApprovalOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}

type AuditEventPager struct {
	Order  auditevent.OrderOption
	Filter func(*AuditEventQuery) (*AuditEventQuery, error)
}

// AuditEventPaginateOption enables pagination customization.
type AuditEventPaginateOption func(*AuditEventPager)

// DefaultAuditEventOrder is the default ordering of AuditEvent.
var DefaultAuditEventOrder = Desc(auditevent.FieldID)

func newAuditEventPager(opts []AuditEventPaginateOption) (*AuditEventPager, error) {
	pager := &AuditEventPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultAuditEventOrder
	}
	return pager, nil
}

func (p *AuditEventPager) ApplyFilter(query *AuditEventQuery) (*AuditEventQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// AuditEventPageList is AuditEvent PageList result.
type AuditEventPageList struct {
	List        []*AuditEvent `json:"list"`
	PageDetails *PageDetails  `json:"pageDetails"`
}

func (_m *AuditEventQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...AuditEventPaginateOption,
) (*AuditEventPageList, error) {

	pager, err := newAuditEventPager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &AuditEventPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := _m.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		_m = _m.Order(DefaultAuditEventOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}

type ChatTurnPager struct {
	Order  chatturn.OrderOption
	Filter func(*ChatTurnQuery) (*ChatTurnQuery, error)
}

// ChatTurnPaginateOption enables pagination customization.
type ChatTurnPaginateOption func(*ChatTurnPager)

// DefaultChatTurnOrder is the default ordering of ChatTurn.
var DefaultChatTurnOrder = Desc(chatturn.FieldID)

func newChatTurnPager(opts []ChatTurnPaginateOption) (*ChatTurnPager, error) {
	pager := &ChatTurnPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultChatTurnOrder
	}
	return pager, nil
}

func (p *ChatTurnPager) ApplyFilter(query *ChatTurnQuery) (*ChatTurnQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// ChatTurnPageList is ChatTurn PageList result.
type ChatTurnPageList struct {
	List        []*ChatTurn  `json:"list"`
	PageDetails *PageDetails `json:"pageDetails"`
}

func (_m *ChatTurnQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...ChatTurnPaginateOption,
) (*ChatTurnPageList, error) {

	pager, err := newChatTurnPager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &ChatTurnPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := _m.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		_m = _m.Order(DefaultChatTurnOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}

type CheckpointPager struct {
	Order  checkpoint.OrderOption
	Filter func(*CheckpointQuery) (*CheckpointQuery, error)
}

// CheckpointPaginateOption enables pagination customization.
type CheckpointPaginateOption func(*CheckpointPager)

// DefaultCheckpointOrder is the default ordering of Checkpoint.
var DefaultCheckpointOrder = Desc(checkpoint.FieldID)

func newCheckpointPager(opts []CheckpointPaginateOption) (*CheckpointPager, error) {
	pager := &CheckpointPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultCheckpointOrder
	}
	return pager, nil
}

func (p *CheckpointPager) ApplyFilter(query *CheckpointQuery) (*CheckpointQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// CheckpointPageList is Checkpoint PageList result.
type CheckpointPageList struct {
	List        []*Checkpoint `json:"list"`
	PageDetails *PageDetails  `json:"pageDetails"`
}

func (_m *CheckpointQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...CheckpointPaginateOption,
) (*CheckpointPageList, error) {

	pager, err := newCheckpointPager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &CheckpointPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := _m.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		_m = _m.Order(DefaultCheckpointOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}

type DocumentPager struct {
	Order  document.OrderOption
	Filter func(*DocumentQuery) (*DocumentQuery, error)
}

// DocumentPaginateOption enables pagination customization.
type DocumentPaginateOption func(*DocumentPager)

// DefaultDocumentOrder is the default ordering of Document.
var DefaultDocumentOrder = Desc(document.FieldID)

func newDocumentPager(opts []DocumentPaginateOption) (*DocumentPager, error) {
	pager := &DocumentPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultDocumentOrder
	}
	return pager, nil
}

func (p *DocumentPager) ApplyFilter(query *DocumentQuery) (*DocumentQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// DocumentPageList is Document PageList result.
type DocumentPageList struct {
	List        []*Document  `json:"list"`
	PageDetails *PageDetails `json:"pageDetails"`
}

func (_m *DocumentQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...DocumentPaginateOption,
) (*DocumentPageList, error) {

	pager, err := newDocumentPager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &DocumentPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := _m.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		_m = _m.Order(DefaultDocumentOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}

type DocumentChunkPager struct {
	Order  documentchunk.OrderOption
	Filter func(*DocumentChunkQuery) (*DocumentChunkQuery, error)
}

// DocumentChunkPaginateOption enables pagination customization.
type DocumentChunkPaginateOption func(*DocumentChunkPager)

// DefaultDocumentChunkOrder is the default ordering of DocumentChunk.
var DefaultDocumentChunkOrder = Desc(documentchunk.FieldID)

func newDocumentChunkPager(opts []DocumentChunkPaginateOption) (*DocumentChunkPager, error) {
	pager := &DocumentChunkPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultDocumentChunkOrder
	}
	return pager, nil
}

func (p *DocumentChunkPager) ApplyFilter(query *DocumentChunkQuery) (*DocumentChunkQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// DocumentChunkPageList is DocumentChunk PageList result.
type DocumentChunkPageList struct {
	List        []*DocumentChunk `json:"list"`
	PageDetails *PageDetails     `json:"pageDetails"`
}

func (_m *DocumentChunkQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...DocumentChunkPaginateOption,
) (*DocumentChunkPageList, error) {

	pager, err := newDocumentChunkPager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &DocumentChunkPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := _m.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		_m = _m.Order(DefaultDocumentChunkOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}

type KnowledgeBasePager struct {
	Order  knowledgebase.OrderOption
	Filter func(*KnowledgeBaseQuery) (*KnowledgeBaseQuery, error)
}

// KnowledgeBasePaginateOption enables pagination customization.
type KnowledgeBasePaginateOption func(*KnowledgeBasePager)

// DefaultKnowledgeBaseOrder is the default ordering of KnowledgeBase.
var DefaultKnowledgeBaseOrder = Desc(knowledgebase.FieldID)

func newKnowledgeBasePager(opts []KnowledgeBasePaginateOption) (*KnowledgeBasePager, error) {
	pager := &KnowledgeBasePager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultKnowledgeBaseOrder
	}
	return pager, nil
}

func (p *KnowledgeBasePager) ApplyFilter(query *KnowledgeBaseQuery) (*KnowledgeBaseQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// KnowledgeBasePageList is KnowledgeBase PageList result.
type KnowledgeBasePageList struct {
	List        []*KnowledgeBase `json:"list"`
	PageDetails *PageDetails     `json:"pageDetails"`
}

func (_m *KnowledgeBaseQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...KnowledgeBasePaginateOption,
) (*KnowledgeBasePageList, error) {

	pager, err := newKnowledgeBasePager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &KnowledgeBasePageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := _m.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		_m = _m.Order(DefaultKnowledgeBaseOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}

type KnowledgeFolderPager struct {
	Order  knowledgefolder.OrderOption
	Filter func(*KnowledgeFolderQuery) (*KnowledgeFolderQuery, error)
}

// KnowledgeFolderPaginateOption enables pagination customization.
type KnowledgeFolderPaginateOption func(*KnowledgeFolderPager)

// DefaultKnowledgeFolderOrder is the default ordering of KnowledgeFolder.
var DefaultKnowledgeFolderOrder = Desc(knowledgefolder.FieldID)

func newKnowledgeFolderPager(opts []KnowledgeFolderPaginateOption) (*KnowledgeFolderPager, error) {
	pager := &KnowledgeFolderPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultKnowledgeFolderOrder
	}
	return pager, nil
}

func (p *KnowledgeFolderPager) ApplyFilter(query *KnowledgeFolderQuery) (*KnowledgeFolderQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// KnowledgeFolderPageList is KnowledgeFolder PageList result.
type KnowledgeFolderPageList struct {
	List        []*KnowledgeFolder `json:"list"`
	PageDetails *PageDetails       `json:"pageDetails"`
}

func (_m *KnowledgeFolderQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...KnowledgeFolderPaginateOption,
) (*KnowledgeFolderPageList, error) {

	pager, err := newKnowledgeFolderPager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &KnowledgeFolderPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := _m.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		_m = _m.Order(DefaultKnowledgeFolderOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}

type KnowledgeIndexPager struct {
	Order  knowledgeindex.OrderOption
	Filter func(*KnowledgeIndexQuery) (*KnowledgeIndexQuery, error)
}

// KnowledgeIndexPaginateOption enables pagination customization.
type KnowledgeIndexPaginateOption func(*KnowledgeIndexPager)

// DefaultKnowledgeIndexOrder is the default ordering of KnowledgeIndex.
var DefaultKnowledgeIndexOrder = Desc(knowledgeindex.FieldID)

func newKnowledgeIndexPager(opts []KnowledgeIndexPaginateOption) (*KnowledgeIndexPager, error) {
	pager := &KnowledgeIndexPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultKnowledgeIndexOrder
	}
	return pager, nil
}

func (p *KnowledgeIndexPager) ApplyFilter(query *KnowledgeIndexQuery) (*KnowledgeIndexQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// KnowledgeIndexPageList is KnowledgeIndex PageList result.
type KnowledgeIndexPageList struct {
	List        []*KnowledgeIndex `json:"list"`
	PageDetails *PageDetails      `json:"pageDetails"`
}

func (_m *KnowledgeIndexQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...KnowledgeIndexPaginateOption,
) (*KnowledgeIndexPageList, error) {

	pager, err := newKnowledgeIndexPager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &KnowledgeIndexPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := _m.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		_m = _m.Order(DefaultKnowledgeIndexOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}

type SessionPager struct {
	Order  session.OrderOption
	Filter func(*SessionQuery) (*SessionQuery, error)
}

// SessionPaginateOption enables pagination customization.
type SessionPaginateOption func(*SessionPager)

// DefaultSessionOrder is the default ordering of Session.
var DefaultSessionOrder = Desc(session.FieldID)

func newSessionPager(opts []SessionPaginateOption) (*SessionPager, error) {
	pager := &SessionPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultSessionOrder
	}
	return pager, nil
}

func (p *SessionPager) ApplyFilter(query *SessionQuery) (*SessionQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// SessionPageList is Session PageList result.
type SessionPageList struct {
	List        []*Session   `json:"list"`
	PageDetails *PageDetails `json:"pageDetails"`
}

func (_m *SessionQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...SessionPaginateOption,
) (*SessionPageList, error) {

	pager, err := newSessionPager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &SessionPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := _m.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		_m = _m.Order(DefaultSessionOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}

type SessionMessagePager struct {
	Order  sessionmessage.OrderOption
	Filter func(*SessionMessageQuery) (*SessionMessageQuery, error)
}

// SessionMessagePaginateOption enables pagination customization.
type SessionMessagePaginateOption func(*SessionMessagePager)

// DefaultSessionMessageOrder is the default ordering of SessionMessage.
var DefaultSessionMessageOrder = Desc(sessionmessage.FieldID)

func newSessionMessagePager(opts []SessionMessagePaginateOption) (*SessionMessagePager, error) {
	pager := &SessionMessagePager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultSessionMessageOrder
	}
	return pager, nil
}

func (p *SessionMessagePager) ApplyFilter(query *SessionMessageQuery) (*SessionMessageQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// SessionMessagePageList is SessionMessage PageList result.
type SessionMessagePageList struct {
	List        []*SessionMessage `json:"list"`
	PageDetails *PageDetails      `json:"pageDetails"`
}

func (_m *SessionMessageQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...SessionMessagePaginateOption,
) (*SessionMessagePageList, error) {

	pager, err := newSessionMessagePager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &SessionMessagePageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := _m.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		_m = _m.Order(DefaultSessionMessageOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}

type VectorOutboxPager struct {
	Order  vectoroutbox.OrderOption
	Filter func(*VectorOutboxQuery) (*VectorOutboxQuery, error)
}

// VectorOutboxPaginateOption enables pagination customization.
type VectorOutboxPaginateOption func(*VectorOutboxPager)

// DefaultVectorOutboxOrder is the default ordering of VectorOutbox.
var DefaultVectorOutboxOrder = Desc(vectoroutbox.FieldID)

func newVectorOutboxPager(opts []VectorOutboxPaginateOption) (*VectorOutboxPager, error) {
	pager := &VectorOutboxPager{}
	for _, opt := range opts {
		opt(pager)
	}
	if pager.Order == nil {
		pager.Order = DefaultVectorOutboxOrder
	}
	return pager, nil
}

func (p *VectorOutboxPager) ApplyFilter(query *VectorOutboxQuery) (*VectorOutboxQuery, error) {
	if p.Filter != nil {
		return p.Filter(query)
	}
	return query, nil
}

// VectorOutboxPageList is VectorOutbox PageList result.
type VectorOutboxPageList struct {
	List        []*VectorOutbox `json:"list"`
	PageDetails *PageDetails    `json:"pageDetails"`
}

func (_m *VectorOutboxQuery) Page(
	ctx context.Context, pageNum uint64, pageSize uint64, opts ...VectorOutboxPaginateOption,
) (*VectorOutboxPageList, error) {

	pager, err := newVectorOutboxPager(opts)
	if err != nil {
		return nil, err
	}

	if _m, err = pager.ApplyFilter(_m); err != nil {
		return nil, err
	}

	ret := &VectorOutboxPageList{}

	ret.PageDetails = &PageDetails{
		Page: pageNum,
		Size: pageSize,
	}

	query := _m.Clone()
	query.ctx.Fields = nil
	count, err := query.Count(ctx)

	if err != nil {
		return nil, err
	}

	ret.PageDetails.Total = uint64(count)

	if pager.Order != nil {
		_m = _m.Order(pager.Order)
	} else {
		_m = _m.Order(DefaultVectorOutboxOrder)
	}

	_m = _m.Offset(int((pageNum - 1) * pageSize)).Limit(int(pageSize))
	list, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	ret.List = list

	return ret, nil
}
