// Code generated by ent, DO NOT EDIT.

package ent

import (
	"eino-quickstart/ent/agentdataset"
	"eino-quickstart/ent/agentrun"
	"eino-quickstart/ent/approval"
	"eino-quickstart/ent/auditevent"
	"eino-quickstart/ent/chatturn"
	"eino-quickstart/ent/checkpoint"
	"eino-quickstart/ent/dataset"
	"eino-quickstart/ent/document"
	"eino-quickstart/ent/documentchunk"
	"eino-quickstart/ent/knowledgefolder"
	"eino-quickstart/ent/knowledgeindex"
	"eino-quickstart/ent/schema"
	"eino-quickstart/ent/session"
	"eino-quickstart/ent/sessionmessage"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentdatasetFields := schema.AgentDataset{}.Fields()
	_ = agentdatasetFields
	// agentdatasetDescCreatedAt is the schema descriptor for created_at field.
	agentdatasetDescCreatedAt := agentdatasetFields[3].Descriptor()
	// agentdataset.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentdataset.DefaultCreatedAt = agentdatasetDescCreatedAt.Default.(func() time.Time)
	agentrunFields := schema.AgentRun{}.Fields()
	_ = agentrunFields
	// agentrunDescCreatedAt is the schema descriptor for created_at field.
	agentrunDescCreatedAt := agentrunFields[8].Descriptor()
	// agentrun.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentrun.DefaultCreatedAt = agentrunDescCreatedAt.Default.(func() time.Time)
	// agentrunDescUpdatedAt is the schema descriptor for updated_at field.
	agentrunDescUpdatedAt := agentrunFields[9].Descriptor()
	// agentrun.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentrun.DefaultUpdatedAt = agentrunDescUpdatedAt.Default.(func() time.Time)
	// agentrun.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentrun.UpdateDefaultUpdatedAt = agentrunDescUpdatedAt.UpdateDefault.(func() time.Time)
	approvalFields := schema.Approval{}.Fields()
	_ = approvalFields
	// approvalDescCreatedAt is the schema descriptor for created_at field.
	approvalDescCreatedAt := approvalFields[8].Descriptor()
	// approval.DefaultCreatedAt holds the default value on creation for the created_at field.
	approval.DefaultCreatedAt = approvalDescCreatedAt.Default.(func() time.Time)
	auditeventFields := schema.AuditEvent{}.Fields()
	_ = auditeventFields
	// auditeventDescCreatedAt is the schema descriptor for created_at field.
	auditeventDescCreatedAt := auditeventFields[5].Descriptor()
	// auditevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditevent.DefaultCreatedAt = auditeventDescCreatedAt.Default.(func() time.Time)
	chatturnFields := schema.ChatTurn{}.Fields()
	_ = chatturnFields
	// chatturnDescCreatedAt is the schema descriptor for created_at field.
	chatturnDescCreatedAt := chatturnFields[8].Descriptor()
	// chatturn.DefaultCreatedAt holds the default value on creation for the created_at field.
	chatturn.DefaultCreatedAt = chatturnDescCreatedAt.Default.(func() time.Time)
	checkpointFields := schema.Checkpoint{}.Fields()
	_ = checkpointFields
	// checkpointDescCreatedAt is the schema descriptor for created_at field.
	checkpointDescCreatedAt := checkpointFields[2].Descriptor()
	// checkpoint.DefaultCreatedAt holds the default value on creation for the created_at field.
	checkpoint.DefaultCreatedAt = checkpointDescCreatedAt.Default.(func() time.Time)
	// checkpointDescUpdatedAt is the schema descriptor for updated_at field.
	checkpointDescUpdatedAt := checkpointFields[3].Descriptor()
	// checkpoint.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	checkpoint.DefaultUpdatedAt = checkpointDescUpdatedAt.Default.(func() time.Time)
	// checkpoint.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	checkpoint.UpdateDefaultUpdatedAt = checkpointDescUpdatedAt.UpdateDefault.(func() time.Time)
	datasetFields := schema.Dataset{}.Fields()
	_ = datasetFields
	// datasetDescOwnerSubject is the schema descriptor for owner_subject field.
	datasetDescOwnerSubject := datasetFields[2].Descriptor()
	// dataset.DefaultOwnerSubject holds the default value on creation for the owner_subject field.
	dataset.DefaultOwnerSubject = datasetDescOwnerSubject.Default.(string)
	// datasetDescType is the schema descriptor for type field.
	datasetDescType := datasetFields[5].Descriptor()
	// dataset.DefaultType holds the default value on creation for the type field.
	dataset.DefaultType = datasetDescType.Default.(string)
	// datasetDescCreatedAt is the schema descriptor for created_at field.
	datasetDescCreatedAt := datasetFields[6].Descriptor()
	// dataset.DefaultCreatedAt holds the default value on creation for the created_at field.
	dataset.DefaultCreatedAt = datasetDescCreatedAt.Default.(func() time.Time)
	// datasetDescUpdatedAt is the schema descriptor for updated_at field.
	datasetDescUpdatedAt := datasetFields[7].Descriptor()
	// dataset.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dataset.DefaultUpdatedAt = datasetDescUpdatedAt.Default.(func() time.Time)
	// dataset.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dataset.UpdateDefaultUpdatedAt = datasetDescUpdatedAt.UpdateDefault.(func() time.Time)
	documentFields := schema.Document{}.Fields()
	_ = documentFields
	// documentDescOwnerSubject is the schema descriptor for owner_subject field.
	documentDescOwnerSubject := documentFields[4].Descriptor()
	// document.DefaultOwnerSubject holds the default value on creation for the owner_subject field.
	document.DefaultOwnerSubject = documentDescOwnerSubject.Default.(string)
	// documentDescEnabled is the schema descriptor for enabled field.
	documentDescEnabled := documentFields[7].Descriptor()
	// document.DefaultEnabled holds the default value on creation for the enabled field.
	document.DefaultEnabled = documentDescEnabled.Default.(bool)
	// documentDescDatasetID is the schema descriptor for dataset_id field.
	documentDescDatasetID := documentFields[8].Descriptor()
	// document.DefaultDatasetID holds the default value on creation for the dataset_id field.
	document.DefaultDatasetID = documentDescDatasetID.Default.(uint64)
	// documentDescCreatedAt is the schema descriptor for created_at field.
	documentDescCreatedAt := documentFields[10].Descriptor()
	// document.DefaultCreatedAt holds the default value on creation for the created_at field.
	document.DefaultCreatedAt = documentDescCreatedAt.Default.(func() time.Time)
	// documentDescUpdatedAt is the schema descriptor for updated_at field.
	documentDescUpdatedAt := documentFields[11].Descriptor()
	// document.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	document.DefaultUpdatedAt = documentDescUpdatedAt.Default.(func() time.Time)
	// document.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	document.UpdateDefaultUpdatedAt = documentDescUpdatedAt.UpdateDefault.(func() time.Time)
	documentchunkFields := schema.DocumentChunk{}.Fields()
	_ = documentchunkFields
	// documentchunkDescCreatedAt is the schema descriptor for created_at field.
	documentchunkDescCreatedAt := documentchunkFields[6].Descriptor()
	// documentchunk.DefaultCreatedAt holds the default value on creation for the created_at field.
	documentchunk.DefaultCreatedAt = documentchunkDescCreatedAt.Default.(func() time.Time)
	knowledgefolderFields := schema.KnowledgeFolder{}.Fields()
	_ = knowledgefolderFields
	// knowledgefolderDescSort is the schema descriptor for sort field.
	knowledgefolderDescSort := knowledgefolderFields[2].Descriptor()
	// knowledgefolder.DefaultSort holds the default value on creation for the sort field.
	knowledgefolder.DefaultSort = knowledgefolderDescSort.Default.(int)
	// knowledgefolderDescCreatedAt is the schema descriptor for created_at field.
	knowledgefolderDescCreatedAt := knowledgefolderFields[5].Descriptor()
	// knowledgefolder.DefaultCreatedAt holds the default value on creation for the created_at field.
	knowledgefolder.DefaultCreatedAt = knowledgefolderDescCreatedAt.Default.(func() time.Time)
	// knowledgefolderDescUpdatedAt is the schema descriptor for updated_at field.
	knowledgefolderDescUpdatedAt := knowledgefolderFields[6].Descriptor()
	// knowledgefolder.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	knowledgefolder.DefaultUpdatedAt = knowledgefolderDescUpdatedAt.Default.(func() time.Time)
	// knowledgefolder.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	knowledgefolder.UpdateDefaultUpdatedAt = knowledgefolderDescUpdatedAt.UpdateDefault.(func() time.Time)
	knowledgeindexFields := schema.KnowledgeIndex{}.Fields()
	_ = knowledgeindexFields
	// knowledgeindexDescCreatedAt is the schema descriptor for created_at field.
	knowledgeindexDescCreatedAt := knowledgeindexFields[6].Descriptor()
	// knowledgeindex.DefaultCreatedAt holds the default value on creation for the created_at field.
	knowledgeindex.DefaultCreatedAt = knowledgeindexDescCreatedAt.Default.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescSessionID is the schema descriptor for session_id field.
	sessionDescSessionID := sessionFields[0].Descriptor()
	// session.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	session.SessionIDValidator = sessionDescSessionID.Validators[0].(func(string) error)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[2].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	sessionmessageFields := schema.SessionMessage{}.Fields()
	_ = sessionmessageFields
	// sessionmessageDescRole is the schema descriptor for role field.
	sessionmessageDescRole := sessionmessageFields[0].Descriptor()
	// sessionmessage.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	sessionmessage.RoleValidator = sessionmessageDescRole.Validators[0].(func(string) error)
	// sessionmessageDescContent is the schema descriptor for content field.
	sessionmessageDescContent := sessionmessageFields[1].Descriptor()
	// sessionmessage.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	sessionmessage.ContentValidator = sessionmessageDescContent.Validators[0].(func(string) error)
	// sessionmessageDescCreatedAt is the schema descriptor for created_at field.
	sessionmessageDescCreatedAt := sessionmessageFields[2].Descriptor()
	// sessionmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	sessionmessage.DefaultCreatedAt = sessionmessageDescCreatedAt.Default.(func() time.Time)
}
