// Code generated by ent, DO NOT EDIT.

package ent

import (
	"eino-quickstart/ent/agentrun"
	"eino-quickstart/ent/approval"
	"eino-quickstart/ent/chatturn"
	"eino-quickstart/ent/dataset"
	"eino-quickstart/ent/document"
	"eino-quickstart/ent/documentchunk"
	"eino-quickstart/ent/knowledgeindex"
	"time"
)

// set field if value's pointer is not nil.
func (_m *AgentDatasetUpdate) SetNotNilDatasetID(value *uint64) *AgentDatasetUpdate {
	if value != nil {
		return _m.SetDatasetID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentDatasetUpdateOne) SetNotNilDatasetID(value *uint64) *AgentDatasetUpdateOne {
	if value != nil {
		return _m.SetDatasetID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentDatasetCreate) SetNotNilDatasetID(value *uint64) *AgentDatasetCreate {
	if value != nil {
		return _m.SetDatasetID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunUpdate) SetNotNilStatus(value *agentrun.Status) *AgentRunUpdate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunUpdateOne) SetNotNilStatus(value *agentrun.Status) *AgentRunUpdateOne {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunCreate) SetNotNilStatus(value *agentrun.Status) *AgentRunCreate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunUpdate) SetNotNilApprovalID(value *string) *AgentRunUpdate {
	if value != nil {
		return _m.SetApprovalID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunUpdateOne) SetNotNilApprovalID(value *string) *AgentRunUpdateOne {
	if value != nil {
		return _m.SetApprovalID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunCreate) SetNotNilApprovalID(value *string) *AgentRunCreate {
	if value != nil {
		return _m.SetApprovalID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunUpdate) SetNotNilErrorCode(value *string) *AgentRunUpdate {
	if value != nil {
		return _m.SetErrorCode(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunUpdateOne) SetNotNilErrorCode(value *string) *AgentRunUpdateOne {
	if value != nil {
		return _m.SetErrorCode(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunCreate) SetNotNilErrorCode(value *string) *AgentRunCreate {
	if value != nil {
		return _m.SetErrorCode(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunUpdate) SetNotNilUpdatedAt(value *time.Time) *AgentRunUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunUpdateOne) SetNotNilUpdatedAt(value *time.Time) *AgentRunUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunCreate) SetNotNilUpdatedAt(value *time.Time) *AgentRunCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunUpdate) SetNotNilCompletedAt(value *time.Time) *AgentRunUpdate {
	if value != nil {
		return _m.SetCompletedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunUpdateOne) SetNotNilCompletedAt(value *time.Time) *AgentRunUpdateOne {
	if value != nil {
		return _m.SetCompletedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunCreate) SetNotNilCompletedAt(value *time.Time) *AgentRunCreate {
	if value != nil {
		return _m.SetCompletedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunUpdate) SetNotNilExpiresAt(value *time.Time) *AgentRunUpdate {
	if value != nil {
		return _m.SetExpiresAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunUpdateOne) SetNotNilExpiresAt(value *time.Time) *AgentRunUpdateOne {
	if value != nil {
		return _m.SetExpiresAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AgentRunCreate) SetNotNilExpiresAt(value *time.Time) *AgentRunCreate {
	if value != nil {
		return _m.SetExpiresAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdate) SetNotNilRunID(value *string) *ApprovalUpdate {
	if value != nil {
		return _m.SetRunID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdateOne) SetNotNilRunID(value *string) *ApprovalUpdateOne {
	if value != nil {
		return _m.SetRunID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalCreate) SetNotNilRunID(value *string) *ApprovalCreate {
	if value != nil {
		return _m.SetRunID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdate) SetNotNilTurnID(value *string) *ApprovalUpdate {
	if value != nil {
		return _m.SetTurnID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdateOne) SetNotNilTurnID(value *string) *ApprovalUpdateOne {
	if value != nil {
		return _m.SetTurnID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalCreate) SetNotNilTurnID(value *string) *ApprovalCreate {
	if value != nil {
		return _m.SetTurnID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdate) SetNotNilArgumentsHash(value *string) *ApprovalUpdate {
	if value != nil {
		return _m.SetArgumentsHash(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdateOne) SetNotNilArgumentsHash(value *string) *ApprovalUpdateOne {
	if value != nil {
		return _m.SetArgumentsHash(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalCreate) SetNotNilArgumentsHash(value *string) *ApprovalCreate {
	if value != nil {
		return _m.SetArgumentsHash(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdate) SetNotNilDisplayArguments(value *string) *ApprovalUpdate {
	if value != nil {
		return _m.SetDisplayArguments(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdateOne) SetNotNilDisplayArguments(value *string) *ApprovalUpdateOne {
	if value != nil {
		return _m.SetDisplayArguments(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalCreate) SetNotNilDisplayArguments(value *string) *ApprovalCreate {
	if value != nil {
		return _m.SetDisplayArguments(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdate) SetNotNilStatus(value *approval.Status) *ApprovalUpdate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdateOne) SetNotNilStatus(value *approval.Status) *ApprovalUpdateOne {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalCreate) SetNotNilStatus(value *approval.Status) *ApprovalCreate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdate) SetNotNilDecidedAt(value *time.Time) *ApprovalUpdate {
	if value != nil {
		return _m.SetDecidedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdateOne) SetNotNilDecidedAt(value *time.Time) *ApprovalUpdateOne {
	if value != nil {
		return _m.SetDecidedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalCreate) SetNotNilDecidedAt(value *time.Time) *ApprovalCreate {
	if value != nil {
		return _m.SetDecidedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdate) SetNotNilExecutedAt(value *time.Time) *ApprovalUpdate {
	if value != nil {
		return _m.SetExecutedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdateOne) SetNotNilExecutedAt(value *time.Time) *ApprovalUpdateOne {
	if value != nil {
		return _m.SetExecutedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalCreate) SetNotNilExecutedAt(value *time.Time) *ApprovalCreate {
	if value != nil {
		return _m.SetExecutedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdate) SetNotNilDecidedBy(value *string) *ApprovalUpdate {
	if value != nil {
		return _m.SetDecidedBy(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdateOne) SetNotNilDecidedBy(value *string) *ApprovalUpdateOne {
	if value != nil {
		return _m.SetDecidedBy(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalCreate) SetNotNilDecidedBy(value *string) *ApprovalCreate {
	if value != nil {
		return _m.SetDecidedBy(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdate) SetNotNilCheckpointID(value *string) *ApprovalUpdate {
	if value != nil {
		return _m.SetCheckpointID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdateOne) SetNotNilCheckpointID(value *string) *ApprovalUpdateOne {
	if value != nil {
		return _m.SetCheckpointID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalCreate) SetNotNilCheckpointID(value *string) *ApprovalCreate {
	if value != nil {
		return _m.SetCheckpointID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdate) SetNotNilInterruptID(value *string) *ApprovalUpdate {
	if value != nil {
		return _m.SetInterruptID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdateOne) SetNotNilInterruptID(value *string) *ApprovalUpdateOne {
	if value != nil {
		return _m.SetInterruptID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalCreate) SetNotNilInterruptID(value *string) *ApprovalCreate {
	if value != nil {
		return _m.SetInterruptID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdate) SetNotNilExpiresAt(value *time.Time) *ApprovalUpdate {
	if value != nil {
		return _m.SetExpiresAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalUpdateOne) SetNotNilExpiresAt(value *time.Time) *ApprovalUpdateOne {
	if value != nil {
		return _m.SetExpiresAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ApprovalCreate) SetNotNilExpiresAt(value *time.Time) *ApprovalCreate {
	if value != nil {
		return _m.SetExpiresAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventUpdate) SetNotNilSessionID(value *string) *AuditEventUpdate {
	if value != nil {
		return _m.SetSessionID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventUpdateOne) SetNotNilSessionID(value *string) *AuditEventUpdateOne {
	if value != nil {
		return _m.SetSessionID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventCreate) SetNotNilSessionID(value *string) *AuditEventCreate {
	if value != nil {
		return _m.SetSessionID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventUpdate) SetNotNilApprovalID(value *string) *AuditEventUpdate {
	if value != nil {
		return _m.SetApprovalID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventUpdateOne) SetNotNilApprovalID(value *string) *AuditEventUpdateOne {
	if value != nil {
		return _m.SetApprovalID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventCreate) SetNotNilApprovalID(value *string) *AuditEventCreate {
	if value != nil {
		return _m.SetApprovalID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventUpdate) SetNotNilEventType(value *string) *AuditEventUpdate {
	if value != nil {
		return _m.SetEventType(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventUpdateOne) SetNotNilEventType(value *string) *AuditEventUpdateOne {
	if value != nil {
		return _m.SetEventType(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventCreate) SetNotNilEventType(value *string) *AuditEventCreate {
	if value != nil {
		return _m.SetEventType(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventUpdate) SetNotNilTool(value *string) *AuditEventUpdate {
	if value != nil {
		return _m.SetTool(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventUpdateOne) SetNotNilTool(value *string) *AuditEventUpdateOne {
	if value != nil {
		return _m.SetTool(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventCreate) SetNotNilTool(value *string) *AuditEventCreate {
	if value != nil {
		return _m.SetTool(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventUpdate) SetNotNilPayload(value *string) *AuditEventUpdate {
	if value != nil {
		return _m.SetPayload(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventUpdateOne) SetNotNilPayload(value *string) *AuditEventUpdateOne {
	if value != nil {
		return _m.SetPayload(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventCreate) SetNotNilPayload(value *string) *AuditEventCreate {
	if value != nil {
		return _m.SetPayload(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventUpdate) SetNotNilActorSubject(value *string) *AuditEventUpdate {
	if value != nil {
		return _m.SetActorSubject(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventUpdateOne) SetNotNilActorSubject(value *string) *AuditEventUpdateOne {
	if value != nil {
		return _m.SetActorSubject(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *AuditEventCreate) SetNotNilActorSubject(value *string) *AuditEventCreate {
	if value != nil {
		return _m.SetActorSubject(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnUpdate) SetNotNilAssistantContent(value *string) *ChatTurnUpdate {
	if value != nil {
		return _m.SetAssistantContent(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnUpdateOne) SetNotNilAssistantContent(value *string) *ChatTurnUpdateOne {
	if value != nil {
		return _m.SetAssistantContent(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnCreate) SetNotNilAssistantContent(value *string) *ChatTurnCreate {
	if value != nil {
		return _m.SetAssistantContent(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnUpdate) SetNotNilStatus(value *chatturn.Status) *ChatTurnUpdate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnUpdateOne) SetNotNilStatus(value *chatturn.Status) *ChatTurnUpdateOne {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnCreate) SetNotNilStatus(value *chatturn.Status) *ChatTurnCreate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnUpdate) SetNotNilApprovalID(value *string) *ChatTurnUpdate {
	if value != nil {
		return _m.SetApprovalID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnUpdateOne) SetNotNilApprovalID(value *string) *ChatTurnUpdateOne {
	if value != nil {
		return _m.SetApprovalID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnCreate) SetNotNilApprovalID(value *string) *ChatTurnCreate {
	if value != nil {
		return _m.SetApprovalID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnUpdate) SetNotNilCheckpointID(value *string) *ChatTurnUpdate {
	if value != nil {
		return _m.SetCheckpointID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnUpdateOne) SetNotNilCheckpointID(value *string) *ChatTurnUpdateOne {
	if value != nil {
		return _m.SetCheckpointID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnCreate) SetNotNilCheckpointID(value *string) *ChatTurnCreate {
	if value != nil {
		return _m.SetCheckpointID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnUpdate) SetNotNilCompletedAt(value *time.Time) *ChatTurnUpdate {
	if value != nil {
		return _m.SetCompletedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnUpdateOne) SetNotNilCompletedAt(value *time.Time) *ChatTurnUpdateOne {
	if value != nil {
		return _m.SetCompletedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *ChatTurnCreate) SetNotNilCompletedAt(value *time.Time) *ChatTurnCreate {
	if value != nil {
		return _m.SetCompletedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CheckpointUpdate) SetNotNilPayload(value []byte) *CheckpointUpdate {
	if value != nil {
		return _m.SetPayload(value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CheckpointUpdateOne) SetNotNilPayload(value []byte) *CheckpointUpdateOne {
	if value != nil {
		return _m.SetPayload(value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CheckpointCreate) SetNotNilPayload(value []byte) *CheckpointCreate {
	if value != nil {
		return _m.SetPayload(value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CheckpointUpdate) SetNotNilUpdatedAt(value *time.Time) *CheckpointUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CheckpointUpdateOne) SetNotNilUpdatedAt(value *time.Time) *CheckpointUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CheckpointCreate) SetNotNilUpdatedAt(value *time.Time) *CheckpointCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CheckpointUpdate) SetNotNilExpiresAt(value *time.Time) *CheckpointUpdate {
	if value != nil {
		return _m.SetExpiresAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CheckpointUpdateOne) SetNotNilExpiresAt(value *time.Time) *CheckpointUpdateOne {
	if value != nil {
		return _m.SetExpiresAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *CheckpointCreate) SetNotNilExpiresAt(value *time.Time) *CheckpointCreate {
	if value != nil {
		return _m.SetExpiresAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdate) SetNotNilName(value *string) *DatasetUpdate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdateOne) SetNotNilName(value *string) *DatasetUpdateOne {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetCreate) SetNotNilName(value *string) *DatasetCreate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdate) SetNotNilDescription(value *string) *DatasetUpdate {
	if value != nil {
		return _m.SetDescription(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdateOne) SetNotNilDescription(value *string) *DatasetUpdateOne {
	if value != nil {
		return _m.SetDescription(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetCreate) SetNotNilDescription(value *string) *DatasetCreate {
	if value != nil {
		return _m.SetDescription(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdate) SetNotNilOwnerSubject(value *string) *DatasetUpdate {
	if value != nil {
		return _m.SetOwnerSubject(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdateOne) SetNotNilOwnerSubject(value *string) *DatasetUpdateOne {
	if value != nil {
		return _m.SetOwnerSubject(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetCreate) SetNotNilOwnerSubject(value *string) *DatasetCreate {
	if value != nil {
		return _m.SetOwnerSubject(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdate) SetNotNilVisibility(value *dataset.Visibility) *DatasetUpdate {
	if value != nil {
		return _m.SetVisibility(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdateOne) SetNotNilVisibility(value *dataset.Visibility) *DatasetUpdateOne {
	if value != nil {
		return _m.SetVisibility(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetCreate) SetNotNilVisibility(value *dataset.Visibility) *DatasetCreate {
	if value != nil {
		return _m.SetVisibility(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdate) SetNotNilStatus(value *dataset.Status) *DatasetUpdate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdateOne) SetNotNilStatus(value *dataset.Status) *DatasetUpdateOne {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetCreate) SetNotNilStatus(value *dataset.Status) *DatasetCreate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdate) SetNotNilType(value *string) *DatasetUpdate {
	if value != nil {
		return _m.SetType(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdateOne) SetNotNilType(value *string) *DatasetUpdateOne {
	if value != nil {
		return _m.SetType(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetCreate) SetNotNilType(value *string) *DatasetCreate {
	if value != nil {
		return _m.SetType(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdate) SetNotNilUpdatedAt(value *time.Time) *DatasetUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetUpdateOne) SetNotNilUpdatedAt(value *time.Time) *DatasetUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DatasetCreate) SetNotNilUpdatedAt(value *time.Time) *DatasetCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdate) SetNotNilSource(value *string) *DocumentUpdate {
	if value != nil {
		return _m.SetSource(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdateOne) SetNotNilSource(value *string) *DocumentUpdateOne {
	if value != nil {
		return _m.SetSource(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentCreate) SetNotNilSource(value *string) *DocumentCreate {
	if value != nil {
		return _m.SetSource(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdate) SetNotNilTitle(value *string) *DocumentUpdate {
	if value != nil {
		return _m.SetTitle(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdateOne) SetNotNilTitle(value *string) *DocumentUpdateOne {
	if value != nil {
		return _m.SetTitle(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentCreate) SetNotNilTitle(value *string) *DocumentCreate {
	if value != nil {
		return _m.SetTitle(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdate) SetNotNilMetadata(value *map[string]interface{}) *DocumentUpdate {
	if value != nil {
		return _m.SetMetadata(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdateOne) SetNotNilMetadata(value *map[string]interface{}) *DocumentUpdateOne {
	if value != nil {
		return _m.SetMetadata(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentCreate) SetNotNilMetadata(value *map[string]interface{}) *DocumentCreate {
	if value != nil {
		return _m.SetMetadata(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdate) SetNotNilOwnerSubject(value *string) *DocumentUpdate {
	if value != nil {
		return _m.SetOwnerSubject(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdateOne) SetNotNilOwnerSubject(value *string) *DocumentUpdateOne {
	if value != nil {
		return _m.SetOwnerSubject(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentCreate) SetNotNilOwnerSubject(value *string) *DocumentCreate {
	if value != nil {
		return _m.SetOwnerSubject(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdate) SetNotNilVisibility(value *document.Visibility) *DocumentUpdate {
	if value != nil {
		return _m.SetVisibility(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdateOne) SetNotNilVisibility(value *document.Visibility) *DocumentUpdateOne {
	if value != nil {
		return _m.SetVisibility(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentCreate) SetNotNilVisibility(value *document.Visibility) *DocumentCreate {
	if value != nil {
		return _m.SetVisibility(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdate) SetNotNilStatus(value *document.Status) *DocumentUpdate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdateOne) SetNotNilStatus(value *document.Status) *DocumentUpdateOne {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentCreate) SetNotNilStatus(value *document.Status) *DocumentCreate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdate) SetNotNilDatasetID(value *uint64) *DocumentUpdate {
	if value != nil {
		return _m.SetDatasetID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdateOne) SetNotNilDatasetID(value *uint64) *DocumentUpdateOne {
	if value != nil {
		return _m.SetDatasetID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentCreate) SetNotNilDatasetID(value *uint64) *DocumentCreate {
	if value != nil {
		return _m.SetDatasetID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdate) SetNotNilFolderID(value *uint64) *DocumentUpdate {
	if value != nil {
		return _m.SetFolderID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdateOne) SetNotNilFolderID(value *uint64) *DocumentUpdateOne {
	if value != nil {
		return _m.SetFolderID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentCreate) SetNotNilFolderID(value *uint64) *DocumentCreate {
	if value != nil {
		return _m.SetFolderID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdate) SetNotNilUpdatedAt(value *time.Time) *DocumentUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentUpdateOne) SetNotNilUpdatedAt(value *time.Time) *DocumentUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentCreate) SetNotNilUpdatedAt(value *time.Time) *DocumentCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkUpdate) SetNotNilContent(value *string) *DocumentChunkUpdate {
	if value != nil {
		return _m.SetContent(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkUpdateOne) SetNotNilContent(value *string) *DocumentChunkUpdateOne {
	if value != nil {
		return _m.SetContent(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkCreate) SetNotNilContent(value *string) *DocumentChunkCreate {
	if value != nil {
		return _m.SetContent(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkUpdate) SetNotNilHeadingPath(value *string) *DocumentChunkUpdate {
	if value != nil {
		return _m.SetHeadingPath(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkUpdateOne) SetNotNilHeadingPath(value *string) *DocumentChunkUpdateOne {
	if value != nil {
		return _m.SetHeadingPath(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkCreate) SetNotNilHeadingPath(value *string) *DocumentChunkCreate {
	if value != nil {
		return _m.SetHeadingPath(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkUpdate) SetNotNilMetadata(value *map[string]interface{}) *DocumentChunkUpdate {
	if value != nil {
		return _m.SetMetadata(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkUpdateOne) SetNotNilMetadata(value *map[string]interface{}) *DocumentChunkUpdateOne {
	if value != nil {
		return _m.SetMetadata(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkCreate) SetNotNilMetadata(value *map[string]interface{}) *DocumentChunkCreate {
	if value != nil {
		return _m.SetMetadata(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkUpdate) SetNotNilVectorStatus(value *documentchunk.VectorStatus) *DocumentChunkUpdate {
	if value != nil {
		return _m.SetVectorStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkUpdateOne) SetNotNilVectorStatus(value *documentchunk.VectorStatus) *DocumentChunkUpdateOne {
	if value != nil {
		return _m.SetVectorStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkCreate) SetNotNilVectorStatus(value *documentchunk.VectorStatus) *DocumentChunkCreate {
	if value != nil {
		return _m.SetVectorStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkUpdate) SetNotNilIndexedAt(value *time.Time) *DocumentChunkUpdate {
	if value != nil {
		return _m.SetIndexedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkUpdateOne) SetNotNilIndexedAt(value *time.Time) *DocumentChunkUpdateOne {
	if value != nil {
		return _m.SetIndexedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *DocumentChunkCreate) SetNotNilIndexedAt(value *time.Time) *DocumentChunkCreate {
	if value != nil {
		return _m.SetIndexedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderUpdate) SetNotNilName(value *string) *KnowledgeFolderUpdate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderUpdateOne) SetNotNilName(value *string) *KnowledgeFolderUpdateOne {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderCreate) SetNotNilName(value *string) *KnowledgeFolderCreate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderUpdate) SetNotNilPath(value *string) *KnowledgeFolderUpdate {
	if value != nil {
		return _m.SetPath(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderUpdateOne) SetNotNilPath(value *string) *KnowledgeFolderUpdateOne {
	if value != nil {
		return _m.SetPath(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderCreate) SetNotNilPath(value *string) *KnowledgeFolderCreate {
	if value != nil {
		return _m.SetPath(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderUpdate) SetNotNilSort(value *int) *KnowledgeFolderUpdate {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderUpdateOne) SetNotNilSort(value *int) *KnowledgeFolderUpdateOne {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderCreate) SetNotNilSort(value *int) *KnowledgeFolderCreate {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderUpdate) SetNotNilDatasetID(value *uint64) *KnowledgeFolderUpdate {
	if value != nil {
		return _m.SetDatasetID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderUpdateOne) SetNotNilDatasetID(value *uint64) *KnowledgeFolderUpdateOne {
	if value != nil {
		return _m.SetDatasetID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderCreate) SetNotNilDatasetID(value *uint64) *KnowledgeFolderCreate {
	if value != nil {
		return _m.SetDatasetID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderUpdate) SetNotNilParentID(value *uint64) *KnowledgeFolderUpdate {
	if value != nil {
		return _m.SetParentID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderUpdateOne) SetNotNilParentID(value *uint64) *KnowledgeFolderUpdateOne {
	if value != nil {
		return _m.SetParentID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderCreate) SetNotNilParentID(value *uint64) *KnowledgeFolderCreate {
	if value != nil {
		return _m.SetParentID(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderUpdate) SetNotNilUpdatedAt(value *time.Time) *KnowledgeFolderUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderUpdateOne) SetNotNilUpdatedAt(value *time.Time) *KnowledgeFolderUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeFolderCreate) SetNotNilUpdatedAt(value *time.Time) *KnowledgeFolderCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexUpdate) SetNotNilMilvusCollection(value *string) *KnowledgeIndexUpdate {
	if value != nil {
		return _m.SetMilvusCollection(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexUpdateOne) SetNotNilMilvusCollection(value *string) *KnowledgeIndexUpdateOne {
	if value != nil {
		return _m.SetMilvusCollection(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexCreate) SetNotNilMilvusCollection(value *string) *KnowledgeIndexCreate {
	if value != nil {
		return _m.SetMilvusCollection(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexUpdate) SetNotNilEmbeddingModel(value *string) *KnowledgeIndexUpdate {
	if value != nil {
		return _m.SetEmbeddingModel(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexUpdateOne) SetNotNilEmbeddingModel(value *string) *KnowledgeIndexUpdateOne {
	if value != nil {
		return _m.SetEmbeddingModel(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexCreate) SetNotNilEmbeddingModel(value *string) *KnowledgeIndexCreate {
	if value != nil {
		return _m.SetEmbeddingModel(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexUpdate) SetNotNilEmbeddingDimensions(value *int) *KnowledgeIndexUpdate {
	if value != nil {
		return _m.SetEmbeddingDimensions(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexUpdateOne) SetNotNilEmbeddingDimensions(value *int) *KnowledgeIndexUpdateOne {
	if value != nil {
		return _m.SetEmbeddingDimensions(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexCreate) SetNotNilEmbeddingDimensions(value *int) *KnowledgeIndexCreate {
	if value != nil {
		return _m.SetEmbeddingDimensions(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexUpdate) SetNotNilStatus(value *knowledgeindex.Status) *KnowledgeIndexUpdate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexUpdateOne) SetNotNilStatus(value *knowledgeindex.Status) *KnowledgeIndexUpdateOne {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexCreate) SetNotNilStatus(value *knowledgeindex.Status) *KnowledgeIndexCreate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexUpdate) SetNotNilActivatedAt(value *time.Time) *KnowledgeIndexUpdate {
	if value != nil {
		return _m.SetActivatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexUpdateOne) SetNotNilActivatedAt(value *time.Time) *KnowledgeIndexUpdateOne {
	if value != nil {
		return _m.SetActivatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *KnowledgeIndexCreate) SetNotNilActivatedAt(value *time.Time) *KnowledgeIndexCreate {
	if value != nil {
		return _m.SetActivatedAt(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *SessionMessageUpdate) SetNotNilRole(value *string) *SessionMessageUpdate {
	if value != nil {
		return _m.SetRole(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *SessionMessageUpdateOne) SetNotNilRole(value *string) *SessionMessageUpdateOne {
	if value != nil {
		return _m.SetRole(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *SessionMessageCreate) SetNotNilRole(value *string) *SessionMessageCreate {
	if value != nil {
		return _m.SetRole(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *SessionMessageUpdate) SetNotNilContent(value *string) *SessionMessageUpdate {
	if value != nil {
		return _m.SetContent(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *SessionMessageUpdateOne) SetNotNilContent(value *string) *SessionMessageUpdateOne {
	if value != nil {
		return _m.SetContent(*value)
	}
	return _m
}

// set field if value's pointer is not nil.
func (_m *SessionMessageCreate) SetNotNilContent(value *string) *SessionMessageCreate {
	if value != nil {
		return _m.SetContent(*value)
	}
	return _m
}
