// Code generated by ent, DO NOT EDIT.

package agentknowledgebase

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the agentknowledgebase type in the database.
	Label = "agent_knowledge_base"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldKnowledgeBaseID holds the string denoting the knowledge_base_id field in the database.
	FieldKnowledgeBaseID = "knowledge_base_id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeKnowledgeBase holds the string denoting the knowledge_base edge name in mutations.
	EdgeKnowledgeBase = "knowledge_base"
	// Table holds the table name of the agentknowledgebase in the database.
	Table = "agent_knowledge_bases"
	// KnowledgeBaseTable is the table that holds the knowledge_base relation/edge.
	KnowledgeBaseTable = "agent_knowledge_bases"
	// KnowledgeBaseInverseTable is the table name for the KnowledgeBase entity.
	// It exists in this package in order to avoid circular dependency with the "knowledgebase" package.
	KnowledgeBaseInverseTable = "knowledge_bases"
	// KnowledgeBaseColumn is the table column denoting the knowledge_base relation/edge.
	KnowledgeBaseColumn = "knowledge_base_id"
)

// Columns holds all SQL columns for agentknowledgebase fields.
var Columns = []string{
	FieldID,
	FieldSubject,
	FieldKnowledgeBaseID,
	FieldCreatedBy,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the AgentKnowledgeBase queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByKnowledgeBaseID orders the results by the knowledge_base_id field.
func ByKnowledgeBaseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKnowledgeBaseID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByKnowledgeBaseField orders the results by knowledge_base field.
func ByKnowledgeBaseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newKnowledgeBaseStep(), sql.OrderByField(field, opts...))
	}
}
func newKnowledgeBaseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(KnowledgeBaseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, KnowledgeBaseTable, KnowledgeBaseColumn),
	)
}
