// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"eino-quickstart/ent"
	"eino-quickstart/ent/agentrun"
	"eino-quickstart/ent/approval"
	"eino-quickstart/ent/auditevent"
	"eino-quickstart/ent/chatturn"
	"eino-quickstart/ent/checkpoint"
	"eino-quickstart/ent/document"
	"eino-quickstart/ent/documentchunk"
	"eino-quickstart/ent/knowledgebase"
	"eino-quickstart/ent/knowledgefolder"
	"eino-quickstart/ent/knowledgeindex"
	"eino-quickstart/ent/predicate"
	"eino-quickstart/ent/session"
	"eino-quickstart/ent/sessionmessage"
	"eino-quickstart/ent/vectoroutbox"

	"entgo.io/ent/dialect/sql"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The AgentRunFunc type is an adapter to allow the use of ordinary function as a Querier.
type AgentRunFunc func(context.Context, *ent.AgentRunQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AgentRunFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AgentRunQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AgentRunQuery", q)
}

// The TraverseAgentRun type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAgentRun func(context.Context, *ent.AgentRunQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAgentRun) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAgentRun) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AgentRunQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AgentRunQuery", q)
}

// The ApprovalFunc type is an adapter to allow the use of ordinary function as a Querier.
type ApprovalFunc func(context.Context, *ent.ApprovalQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ApprovalFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ApprovalQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ApprovalQuery", q)
}

// The TraverseApproval type is an adapter to allow the use of ordinary function as Traverser.
type TraverseApproval func(context.Context, *ent.ApprovalQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseApproval) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseApproval) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ApprovalQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ApprovalQuery", q)
}

// The AuditEventFunc type is an adapter to allow the use of ordinary function as a Querier.
type AuditEventFunc func(context.Context, *ent.AuditEventQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AuditEventFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AuditEventQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AuditEventQuery", q)
}

// The TraverseAuditEvent type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAuditEvent func(context.Context, *ent.AuditEventQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAuditEvent) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAuditEvent) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AuditEventQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AuditEventQuery", q)
}

// The ChatTurnFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChatTurnFunc func(context.Context, *ent.ChatTurnQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ChatTurnFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ChatTurnQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ChatTurnQuery", q)
}

// The TraverseChatTurn type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChatTurn func(context.Context, *ent.ChatTurnQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChatTurn) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChatTurn) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ChatTurnQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ChatTurnQuery", q)
}

// The CheckpointFunc type is an adapter to allow the use of ordinary function as a Querier.
type CheckpointFunc func(context.Context, *ent.CheckpointQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f CheckpointFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.CheckpointQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.CheckpointQuery", q)
}

// The TraverseCheckpoint type is an adapter to allow the use of ordinary function as Traverser.
type TraverseCheckpoint func(context.Context, *ent.CheckpointQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseCheckpoint) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseCheckpoint) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CheckpointQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.CheckpointQuery", q)
}

// The DocumentFunc type is an adapter to allow the use of ordinary function as a Querier.
type DocumentFunc func(context.Context, *ent.DocumentQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f DocumentFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.DocumentQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.DocumentQuery", q)
}

// The TraverseDocument type is an adapter to allow the use of ordinary function as Traverser.
type TraverseDocument func(context.Context, *ent.DocumentQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseDocument) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseDocument) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.DocumentQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.DocumentQuery", q)
}

// The DocumentChunkFunc type is an adapter to allow the use of ordinary function as a Querier.
type DocumentChunkFunc func(context.Context, *ent.DocumentChunkQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f DocumentChunkFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.DocumentChunkQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.DocumentChunkQuery", q)
}

// The TraverseDocumentChunk type is an adapter to allow the use of ordinary function as Traverser.
type TraverseDocumentChunk func(context.Context, *ent.DocumentChunkQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseDocumentChunk) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseDocumentChunk) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.DocumentChunkQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.DocumentChunkQuery", q)
}

// The KnowledgeBaseFunc type is an adapter to allow the use of ordinary function as a Querier.
type KnowledgeBaseFunc func(context.Context, *ent.KnowledgeBaseQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f KnowledgeBaseFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.KnowledgeBaseQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.KnowledgeBaseQuery", q)
}

// The TraverseKnowledgeBase type is an adapter to allow the use of ordinary function as Traverser.
type TraverseKnowledgeBase func(context.Context, *ent.KnowledgeBaseQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseKnowledgeBase) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseKnowledgeBase) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.KnowledgeBaseQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.KnowledgeBaseQuery", q)
}

// The KnowledgeFolderFunc type is an adapter to allow the use of ordinary function as a Querier.
type KnowledgeFolderFunc func(context.Context, *ent.KnowledgeFolderQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f KnowledgeFolderFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.KnowledgeFolderQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.KnowledgeFolderQuery", q)
}

// The TraverseKnowledgeFolder type is an adapter to allow the use of ordinary function as Traverser.
type TraverseKnowledgeFolder func(context.Context, *ent.KnowledgeFolderQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseKnowledgeFolder) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseKnowledgeFolder) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.KnowledgeFolderQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.KnowledgeFolderQuery", q)
}

// The KnowledgeIndexFunc type is an adapter to allow the use of ordinary function as a Querier.
type KnowledgeIndexFunc func(context.Context, *ent.KnowledgeIndexQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f KnowledgeIndexFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.KnowledgeIndexQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.KnowledgeIndexQuery", q)
}

// The TraverseKnowledgeIndex type is an adapter to allow the use of ordinary function as Traverser.
type TraverseKnowledgeIndex func(context.Context, *ent.KnowledgeIndexQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseKnowledgeIndex) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseKnowledgeIndex) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.KnowledgeIndexQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.KnowledgeIndexQuery", q)
}

// The SessionFunc type is an adapter to allow the use of ordinary function as a Querier.
type SessionFunc func(context.Context, *ent.SessionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SessionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SessionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SessionQuery", q)
}

// The TraverseSession type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSession func(context.Context, *ent.SessionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSession) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSession) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SessionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SessionQuery", q)
}

// The SessionMessageFunc type is an adapter to allow the use of ordinary function as a Querier.
type SessionMessageFunc func(context.Context, *ent.SessionMessageQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SessionMessageFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SessionMessageQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SessionMessageQuery", q)
}

// The TraverseSessionMessage type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSessionMessage func(context.Context, *ent.SessionMessageQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSessionMessage) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSessionMessage) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SessionMessageQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SessionMessageQuery", q)
}

// The VectorOutboxFunc type is an adapter to allow the use of ordinary function as a Querier.
type VectorOutboxFunc func(context.Context, *ent.VectorOutboxQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f VectorOutboxFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.VectorOutboxQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.VectorOutboxQuery", q)
}

// The TraverseVectorOutbox type is an adapter to allow the use of ordinary function as Traverser.
type TraverseVectorOutbox func(context.Context, *ent.VectorOutboxQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseVectorOutbox) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseVectorOutbox) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.VectorOutboxQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.VectorOutboxQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.AgentRunQuery:
		return &query[*ent.AgentRunQuery, predicate.AgentRun, agentrun.OrderOption]{typ: ent.TypeAgentRun, tq: q}, nil
	case *ent.ApprovalQuery:
		return &query[*ent.ApprovalQuery, predicate.Approval, approval.OrderOption]{typ: ent.TypeApproval, tq: q}, nil
	case *ent.AuditEventQuery:
		return &query[*ent.AuditEventQuery, predicate.AuditEvent, auditevent.OrderOption]{typ: ent.TypeAuditEvent, tq: q}, nil
	case *ent.ChatTurnQuery:
		return &query[*ent.ChatTurnQuery, predicate.ChatTurn, chatturn.OrderOption]{typ: ent.TypeChatTurn, tq: q}, nil
	case *ent.CheckpointQuery:
		return &query[*ent.CheckpointQuery, predicate.Checkpoint, checkpoint.OrderOption]{typ: ent.TypeCheckpoint, tq: q}, nil
	case *ent.DocumentQuery:
		return &query[*ent.DocumentQuery, predicate.Document, document.OrderOption]{typ: ent.TypeDocument, tq: q}, nil
	case *ent.DocumentChunkQuery:
		return &query[*ent.DocumentChunkQuery, predicate.DocumentChunk, documentchunk.OrderOption]{typ: ent.TypeDocumentChunk, tq: q}, nil
	case *ent.KnowledgeBaseQuery:
		return &query[*ent.KnowledgeBaseQuery, predicate.KnowledgeBase, knowledgebase.OrderOption]{typ: ent.TypeKnowledgeBase, tq: q}, nil
	case *ent.KnowledgeFolderQuery:
		return &query[*ent.KnowledgeFolderQuery, predicate.KnowledgeFolder, knowledgefolder.OrderOption]{typ: ent.TypeKnowledgeFolder, tq: q}, nil
	case *ent.KnowledgeIndexQuery:
		return &query[*ent.KnowledgeIndexQuery, predicate.KnowledgeIndex, knowledgeindex.OrderOption]{typ: ent.TypeKnowledgeIndex, tq: q}, nil
	case *ent.SessionQuery:
		return &query[*ent.SessionQuery, predicate.Session, session.OrderOption]{typ: ent.TypeSession, tq: q}, nil
	case *ent.SessionMessageQuery:
		return &query[*ent.SessionMessageQuery, predicate.SessionMessage, sessionmessage.OrderOption]{typ: ent.TypeSessionMessage, tq: q}, nil
	case *ent.VectorOutboxQuery:
		return &query[*ent.VectorOutboxQuery, predicate.VectorOutbox, vectoroutbox.OrderOption]{typ: ent.TypeVectorOutbox, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
