// Code generated by ent, DO NOT EDIT.

package knowledgefolder

import (
	"eino-quickstart/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldName, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldPath, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldSort, v))
}

// KnowledgeBaseID applies equality check predicate on the "knowledge_base_id" field. It's identical to KnowledgeBaseIDEQ.
func KnowledgeBaseID(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldKnowledgeBaseID, v))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldParentID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldContainsFold(FieldName, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldContainsFold(FieldPath, v))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLTE(FieldSort, v))
}

// KnowledgeBaseIDEQ applies the EQ predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDEQ(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDNEQ applies the NEQ predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDNEQ(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNEQ(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDIn applies the In predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDIn(vs ...int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldIn(FieldKnowledgeBaseID, vs...))
}

// KnowledgeBaseIDNotIn applies the NotIn predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDNotIn(vs ...int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNotIn(FieldKnowledgeBaseID, vs...))
}

// KnowledgeBaseIDGT applies the GT predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDGT(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGT(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDGTE applies the GTE predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDGTE(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGTE(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDLT applies the LT predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDLT(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLT(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDLTE applies the LTE predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDLTE(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLTE(FieldKnowledgeBaseID, v))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...int) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDIsNil applies the IsNil predicate on the "parent_id" field.
func ParentIDIsNil() predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldIsNull(FieldParentID))
}

// ParentIDNotNil applies the NotNil predicate on the "parent_id" field.
func ParentIDNotNil() predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNotNull(FieldParentID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasKnowledgeBase applies the HasEdge predicate on the "knowledge_base" edge.
func HasKnowledgeBase() predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, KnowledgeBaseTable, KnowledgeBaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKnowledgeBaseWith applies the HasEdge predicate on the "knowledge_base" edge with a given conditions (other predicates).
func HasKnowledgeBaseWith(preds ...predicate.KnowledgeBase) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(func(s *sql.Selector) {
		step := newKnowledgeBaseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParent applies the HasEdge predicate on the "parent" edge.
func HasParent() predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentWith applies the HasEdge predicate on the "parent" edge with a given conditions (other predicates).
func HasParentWith(preds ...predicate.KnowledgeFolder) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(func(s *sql.Selector) {
		step := newParentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChildren applies the HasEdge predicate on the "children" edge.
func HasChildren() predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildrenWith applies the HasEdge predicate on the "children" edge with a given conditions (other predicates).
func HasChildrenWith(preds ...predicate.KnowledgeFolder) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(func(s *sql.Selector) {
		step := newChildrenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDocuments applies the HasEdge predicate on the "documents" edge.
func HasDocuments() predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DocumentsTable, DocumentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDocumentsWith applies the HasEdge predicate on the "documents" edge with a given conditions (other predicates).
func HasDocumentsWith(preds ...predicate.Document) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(func(s *sql.Selector) {
		step := newDocumentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KnowledgeFolder) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KnowledgeFolder) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KnowledgeFolder) predicate.KnowledgeFolder {
	return predicate.KnowledgeFolder(sql.NotPredicates(p))
}
