// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AgentDataset is the predicate function for agentdataset builders.
type AgentDataset func(*sql.Selector)

// AgentRun is the predicate function for agentrun builders.
type AgentRun func(*sql.Selector)

// Approval is the predicate function for approval builders.
type Approval func(*sql.Selector)

// AuditEvent is the predicate function for auditevent builders.
type AuditEvent func(*sql.Selector)

// ChatTurn is the predicate function for chatturn builders.
type ChatTurn func(*sql.Selector)

// Checkpoint is the predicate function for checkpoint builders.
type Checkpoint func(*sql.Selector)

// Dataset is the predicate function for dataset builders.
type Dataset func(*sql.Selector)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// DocumentChunk is the predicate function for documentchunk builders.
type DocumentChunk func(*sql.Selector)

// KnowledgeFolder is the predicate function for knowledgefolder builders.
type KnowledgeFolder func(*sql.Selector)

// KnowledgeIndex is the predicate function for knowledgeindex builders.
type KnowledgeIndex func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// SessionMessage is the predicate function for sessionmessage builders.
type SessionMessage func(*sql.Selector)
